package util

import game.State
import listener.*
import org.bukkit.Material
import org.bukkit.StructureType
import org.bukkit.TreeType
import org.bukkit.enchantments.Enchantment
import org.bukkit.entity.EntityType
import org.bukkit.entity.Player
import org.bukkit.event.Listener
import org.bukkit.potion.PotionEffectType
import org.bukkit.potion.PotionType

enum class Objective(private val builder: ListenerBuilder<*> = NoOpListenerBuilder) {
    ACompleteCatalogueAdvancement(AdvancementListenerBuilder("husbandry/complete_catalogue")),
    AFuriousCocktailAdvancement(AdvancementListenerBuilder("nether/all_potions")),
    ASeedyPlaceAdvancement(AdvancementListenerBuilder("husbandry/plant_seed")),
    ATerribleFortressAdvancement(AdvancementListenerBuilder("nether/find_fortress")),
    AcquireHardwareAdvancement(AdvancementListenerBuilder("story/smelt_iron")),
    ArbalisticAdvancement(AdvancementListenerBuilder("adventure/arbalistic")),
    BeeOurGuestAdvancement(AdvancementListenerBuilder("husbandry/safely_harvest_honey")),
    BestFriendsForeverAdvancement(AdvancementListenerBuilder("husbandry/tame_an_animal")),
    BullseyeAdvancement(AdvancementListenerBuilder("adventure/bullseye")),
    CountryLodeTakeMeHomeAdvancement(AdvancementListenerBuilder("nether/use_lodestone")),
    CoverMeWithDiamondsAdvancement(AdvancementListenerBuilder("story/shiny_gear")),
    DiamondsAdvancement(AdvancementListenerBuilder("story/mine_diamond")),
    EnchanterAdvancement(AdvancementListenerBuilder("story/enchant_item")),
    FishyBusinessAdvancement(AdvancementListenerBuilder("husbandry/fishy_business")),
    GettingAnUpgradeAdvancement(AdvancementListenerBuilder("story/upgrade_tools")),
    GlowAndBeholdAdvancement(AdvancementListenerBuilder("husbandry/make_a_sign_glow")),
    GreatViewFromUpHereAdvancement(AdvancementListenerBuilder("end/levitate")),
    HeroOfTheVillageAdvancement(AdvancementListenerBuilder("adventure/hero_of_the_village")),
    HiddenInTheDepthsAdvancement(AdvancementListenerBuilder("nether/obtain_ancient_debris")),
    HiredHelpAdvancement(AdvancementListenerBuilder("adventure/summon_iron_golem")),
    HotStuffAdvancement(AdvancementListenerBuilder("story/lava_bucket")),
    HotTouristDestinationsAdvancement(AdvancementListenerBuilder("nether/explore_nether")),
    IceBucketChallengeAdvancement(AdvancementListenerBuilder("story/form_obsidian")),
    IntoFireAdvancement(AdvancementListenerBuilder("nether/obtain_blaze_rod")),
    IsItABalloonAdvancement(AdvancementListenerBuilder("adventure/spyglass_at_ghast")),
    IsItAPlaneAdvancement(AdvancementListenerBuilder("adventure/spyglass_at_dragon")),
    IsntItIronPickAdvancement(AdvancementListenerBuilder("story/iron_tools")),
    IsItABirdAdvancement(AdvancementListenerBuilder("adventure/spyglass_at_parrot")),
    LocalBreweryAdvancement(AdvancementListenerBuilder("nether/brew_potion")),
    MonsterHunterAdvancement(AdvancementListenerBuilder("adventure/kill_a_mob")),
    NotQuiteNineLivesAdvancement(AdvancementListenerBuilder("nether/charge_respawn_anchor")),
    NotTodayThankYouAdvancement(AdvancementListenerBuilder("story/deflect_arrow")),
    OhShinyAdvancement(AdvancementListenerBuilder("nether/distract_piglin")),
    OlBetsyAdvancement(AdvancementListenerBuilder("adventure/ol_betsy")),
    PostmortalAdvancement(AdvancementListenerBuilder("adventure/totem_of_undying")),
    RemoteGetawayAdvancement(AdvancementListenerBuilder("end/enter_end_gateway")),
    ReturnToSenderAdvancement(AdvancementListenerBuilder("nether/return_to_sender")),
    SeriousDedicationAdvancement(AdvancementListenerBuilder("husbandry/obtain_netherite_hoe")),
    SkysTheLimitAdvancement(AdvancementListenerBuilder("end/elytra")),
    SniperDuelAdvancement(AdvancementListenerBuilder("adventure/sniper_duel")),
    SpookyScarySkeletonAdvancement(AdvancementListenerBuilder("nether/get_wither_skull")),
    StickySituationAdvancement(AdvancementListenerBuilder("adventure/honey_block_slide")),
    StoneAgeAdvancement(AdvancementListenerBuilder("story/mine_stone")),
    SubspaceBubbleAdvancement(AdvancementListenerBuilder("nether/fast_travel")),
    SuitUpAdvancement(AdvancementListenerBuilder("story/obtain_armor")),
    SweetDreamsAdvancement(AdvancementListenerBuilder("adventure/sleep_in_bed")),
    TacticalFishingAdvancement(AdvancementListenerBuilder("husbandry/tactical_fishing")),
    TakeAimAdvancement(AdvancementListenerBuilder("adventure/shoot_arrow")),
    TheCutestPredatorAdvancement(AdvancementListenerBuilder("husbandry/axolotl_in_a_bucket")),
    TheEndAdvancement(AdvancementListenerBuilder("end/root")),
    TheEndAgainAdvancement(AdvancementListenerBuilder("end/respawn_dragon")),
    TheHealingPowerOfFriendshipAdvancement(AdvancementListenerBuilder("husbandry/kill_axolotl_target")),
    TheNextGenerationAdvancement(AdvancementListenerBuilder("end/dragon_egg")),
    TheParrotsAndTheBatsAdvancement(AdvancementListenerBuilder("husbandry/breed_an_animal")),
    ThisBoatHasLegsAdvancement(AdvancementListenerBuilder("nether/ride_strider")),
    ThoseWereTheDaysAdvancement(AdvancementListenerBuilder("nether/find_bastion")),
    TotalBeelocationAdvancement(AdvancementListenerBuilder("husbandry/silk_touch_nest")),
    TwoBirdsOneArrowAdvancement(AdvancementListenerBuilder("adventure/two_birds_one_arrow")),
    UneasyAllianceAdvancement(AdvancementListenerBuilder("nether/uneasy_alliance")),
    VoluntaryExileAdvancement(AdvancementListenerBuilder("adventure/voluntary_exile")),
    WarPigsAdvancement(AdvancementListenerBuilder("nether/loot_bastion")),
    WaxOffAdvancement(AdvancementListenerBuilder("husbandry/wax_off")),
    WaxOnAdvancement(AdvancementListenerBuilder("husbandry/wax_on")),
    WeNeedToGoDeeperAdvancement(AdvancementListenerBuilder("story/enter_the_nether")),
    WhatADealAdvancement(AdvancementListenerBuilder("adventure/trade")),
    WhateverFloatsYourGoatAdvancement(AdvancementListenerBuilder("husbandry/ride_a_boat_with_a_goat")),
    WhoIsCuttingOnionsAdvancement(AdvancementListenerBuilder("nether/obtain_crying_obsidian")),
    WhosThePillagerNowAdvancement(AdvancementListenerBuilder("adventure/whos_the_pillager_now")),
    WitheringHeightsAdvancement(AdvancementListenerBuilder("nether/summon_wither")),
    YouNeedAMintAdvancement(AdvancementListenerBuilder("end/dragon_breath")),
    ZombieDoctorAdvancement(AdvancementListenerBuilder("story/cure_zombie_villager")),
    UniqueConcreteBlocks12(MultiItemInInventoryListenerBuilder(Constants.Bundles.ConcreteBlocks, 12)),
    BlackStainedGlass16(ItemInInventoryListenerBuilder(Material.BLACK_STAINED_GLASS, 16)),
    BlackWool16(ItemInInventoryListenerBuilder(Material.BLACK_WOOL, 16)),
    BlueIce16(ItemInInventoryListenerBuilder(Material.BLUE_ICE, 16)),
    BlueStainedGlass16(ItemInInventoryListenerBuilder(Material.BLUE_STAINED_GLASS, 16)),
    BlueWool16(ItemInInventoryListenerBuilder(Material.BLUE_WOOL, 16)),
    BrownStainedGlass16(ItemInInventoryListenerBuilder(Material.BROWN_STAINED_GLASS, 16)),
    BrownWool16(ItemInInventoryListenerBuilder(Material.BROWN_WOOL, 16)),
    CyanStainedGlass16(ItemInInventoryListenerBuilder(Material.CYAN_STAINED_GLASS, 16)),
    CyanWool16(ItemInInventoryListenerBuilder(Material.CYAN_WOOL, 16)),
    Eggs16(ItemInInventoryListenerBuilder(Material.EGG, 16)),
    EnderPearls16(ItemInInventoryListenerBuilder(Material.ENDER_PEARL, 16)),
    GrassBlocks16(ItemInInventoryListenerBuilder(Material.GRASS_BLOCK, 16)),
    GrayStainedGlass16(ItemInInventoryListenerBuilder(Material.GRAY_STAINED_GLASS, 16)),
    GrayWool16(ItemInInventoryListenerBuilder(Material.GRAY_WOOL, 16)),
    GreenStainedGlass16(ItemInInventoryListenerBuilder(Material.GREEN_STAINED_GLASS, 16)),
    GreenWool16(ItemInInventoryListenerBuilder(Material.GREEN_WOOL, 16)),
    InkSacks16(ItemInInventoryListenerBuilder(Material.INK_SAC, 16)),
    LightBlueStainedGlass16(ItemInInventoryListenerBuilder(Material.LIGHT_BLUE_STAINED_GLASS, 16)),
    LightBlueWool16(ItemInInventoryListenerBuilder(Material.LIGHT_BLUE_WOOL, 16)),
    LightGrayStainedGlass16(ItemInInventoryListenerBuilder(Material.LIGHT_GRAY_STAINED_GLASS, 16)),
    LightGrayWool16(ItemInInventoryListenerBuilder(Material.LIGHT_GRAY_WOOL, 16)),
    LimeGreenStainedGlass16(ItemInInventoryListenerBuilder(Material.LIME_STAINED_GLASS, 16)),
    LimeGreenWool16(ItemInInventoryListenerBuilder(Material.LIME_WOOL, 16)),
    MagentaStainedGlass16(ItemInInventoryListenerBuilder(Material.MAGENTA_STAINED_GLASS, 16)),
    MagentaWool16(ItemInInventoryListenerBuilder(Material.MAGENTA_WOOL, 16)),
    OrangeStainedGlass16(ItemInInventoryListenerBuilder(Material.ORANGE_STAINED_GLASS, 16)),
    OrangeWool16(ItemInInventoryListenerBuilder(Material.ORANGE_WOOL, 16)),
    PinkStainedGlass16(ItemInInventoryListenerBuilder(Material.PINK_STAINED_GLASS, 16)),
    PinkWool16(ItemInInventoryListenerBuilder(Material.PINK_WOOL, 16)),
    Podzol16(ItemInInventoryListenerBuilder(Material.PODZOL, 16)),
    Pumpkins16(ItemInInventoryListenerBuilder(Material.PUMPKIN, 16)),
    PurpleStainedGlass16(ItemInInventoryListenerBuilder(Material.PURPLE_STAINED_GLASS, 16)),
    PurpleWool16(ItemInInventoryListenerBuilder(Material.PURPLE_WOOL, 16)),
    RedStainedGlass16(ItemInInventoryListenerBuilder(Material.RED_STAINED_GLASS, 16)),
    RedWool16(ItemInInventoryListenerBuilder(Material.RED_WOOL, 16)),
    TintedGlass16(ItemInInventoryListenerBuilder(Material.TINTED_GLASS, 16)),
    WhiteStainedGlass16(ItemInInventoryListenerBuilder(Material.WHITE_STAINED_GLASS, 16)),
    WhiteWool16(ItemInInventoryListenerBuilder(Material.WHITE_WOOL, 16)),
    YellowStainedGlass16(ItemInInventoryListenerBuilder(Material.YELLOW_STAINED_GLASS, 16)),
    YellowWool16(ItemInInventoryListenerBuilder(Material.YELLOW_WOOL, 16)),
    UniqueConcreteBlocks3(MultiItemInInventoryListenerBuilder(Constants.Bundles.ConcreteBlocks, 3)),
    BlazeRods32(ItemInInventoryListenerBuilder(Material.BLAZE_ROD, 32)),
    Diamonds32(ItemInInventoryListenerBuilder(Material.DIAMOND, 32)),
    SpiderEyes32(ItemInInventoryListenerBuilder(Material.SPIDER_EYE, 32)),
    AcaciaLogs64(ItemInInventoryListenerBuilder(Material.ACACIA_LOG, 64)),
    AmethystShards64(ItemInInventoryListenerBuilder(Material.AMETHYST_SHARD, 64)),
    Andesite64(ItemInInventoryListenerBuilder(Material.ANDESITE, 64)),
    Apples64(ItemInInventoryListenerBuilder(Material.APPLE, 64)),
    Arrows64(ItemInInventoryListenerBuilder(Material.ARROW, 64)),
    BirchLogs64(ItemInInventoryListenerBuilder(Material.BIRCH_LOG, 64)),
    Bones64(ItemInInventoryListenerBuilder(Material.BONE, 64)),
    Cacti64(ItemInInventoryListenerBuilder(Material.CACTUS, 64)),
    Carrots64(ItemInInventoryListenerBuilder(Material.CARROTS, 64)),
    Charcoal64(ItemInInventoryListenerBuilder(Material.CHARCOAL, 64)),
    ClayBlocks64(ItemInInventoryListenerBuilder(Material.CLAY, 64)),
    Coal64(ItemInInventoryListenerBuilder(Material.COAL, 64)),
    Cobblestone64(ItemInInventoryListenerBuilder(Material.COBBLESTONE, 64)),
    CopperIngots64(ItemInInventoryListenerBuilder(Material.COPPER_INGOT, 64)),
    CraftingTable64(ItemInInventoryListenerBuilder(Material.CRAFTING_TABLE, 64)),
    CrimsonStems64(ItemInInventoryListenerBuilder(Material.CRIMSON_STEM, 64)),
    DarkOakLogs64(ItemInInventoryListenerBuilder(Material.DARK_OAK_LOG, 64)),
    Diorite64(ItemInInventoryListenerBuilder(Material.DIORITE, 64)),
    Dirt64(ItemInInventoryListenerBuilder(Material.DIRT, 64)),
    Emeralds64(ItemInInventoryListenerBuilder(Material.EMERALD, 64)),
    Endstone64(ItemInInventoryListenerBuilder(Material.END_STONE, 64)),
    Feathers64(ItemInInventoryListenerBuilder(Material.FEATHER, 64)),
    Flint64(ItemInInventoryListenerBuilder(Material.FLINT, 64)),
    Glass64(ItemInInventoryListenerBuilder(Material.GLASS, 64)),
    GlowstoneBlocks64(ItemInInventoryListenerBuilder(Material.GLOWSTONE, 64)),
    GoldIngots64(ItemInInventoryListenerBuilder(Material.GOLD_INGOT, 64)),
    Granite64(ItemInInventoryListenerBuilder(Material.GRANITE, 64)),
    Gravel64(ItemInInventoryListenerBuilder(Material.GRAVEL, 64)),
    Gunpowder64(ItemInInventoryListenerBuilder(Material.GUNPOWDER, 64)),
    IronIngots64(ItemInInventoryListenerBuilder(Material.IRON_INGOT, 64)),
    JungleLogs64(ItemInInventoryListenerBuilder(Material.JUNGLE_LOG, 64)),
    Ladders64(ItemInInventoryListenerBuilder(Material.LADDER, 64)),
    LapisLazuli64(ItemInInventoryListenerBuilder(Material.LAPIS_LAZULI, 64)),
    Leather64(ItemInInventoryListenerBuilder(Material.LEATHER, 64)),
    Leaves64,
    LilyPads64(ItemInInventoryListenerBuilder(Material.LILY_PAD, 64)),
    NetherQuartz64(ItemInInventoryListenerBuilder(Material.QUARTZ, 64)),
    NetherWart64(ItemInInventoryListenerBuilder(Material.NETHER_WART, 64)),
    Netherrack64(ItemInInventoryListenerBuilder(Material.NETHERRACK, 64)),
    OakLogs64(ItemInInventoryListenerBuilder(Material.OAK_LOG, 64)),
    Obsidian64(ItemInInventoryListenerBuilder(Material.OBSIDIAN, 64)),
    Potatoes64(ItemInInventoryListenerBuilder(Material.POTATO, 64)),
    Rails64(ItemInInventoryListenerBuilder(Material.RAIL, 64)),
    Redstone64(ItemInInventoryListenerBuilder(Material.REDSTONE, 64)),
    RottenFlesh64(ItemInInventoryListenerBuilder(Material.ROTTEN_FLESH, 64)),
    Sand64(ItemInInventoryListenerBuilder(Material.SAND, 64)),
    Sandstone64(ItemInInventoryListenerBuilder(Material.SANDSTONE, 64)),
    Slimeballs64(ItemInInventoryListenerBuilder(Material.SLIME_BALL, 64)),
    SmoothStone64(ItemInInventoryListenerBuilder(Material.SMOOTH_STONE, 64)),
    SpruceLogs64(ItemInInventoryListenerBuilder(Material.SPRUCE_LOG, 64)),
    Stone64(ItemInInventoryListenerBuilder(Material.STONE, 64)),
    String64(ItemInInventoryListenerBuilder(Material.STRING, 64)),
    SugarCane64(ItemInInventoryListenerBuilder(Material.SUGAR_CANE, 64)),
    SweetBerries64(ItemInInventoryListenerBuilder(Material.SWEET_BERRIES, 64)),
    WarpedStems64(ItemInInventoryListenerBuilder(Material.WARPED_STEM, 64)),
    Wheat64(ItemInInventoryListenerBuilder(Material.WHEAT, 64)),
    UniqueConcreteBlocks7(MultiItemInInventoryListenerBuilder(Constants.Bundles.ConcreteBlocks, 7)),
    Cobwebs8(ItemInInventoryListenerBuilder(Material.COBWEB, 8)),
    UniqueGlazedTerracotta8(MultiItemInInventoryListenerBuilder(Constants.Bundles.GlazedTerracottaBlocks, 8)),
    Activate3EndPortals,
    All16DyeColors(MultiItemInInventoryListenerBuilder(Constants.Bundles.Dyes)),
    All26UniquePaintings,
    All3Stews(MultiItemInInventoryListenerBuilder(Constants.Bundles.Stews)),
    AllDiamondTools(MultiItemInInventoryListenerBuilder(Constants.Bundles.DiamondTools)),
    AllIronTools(MultiItemInInventoryListenerBuilder(Constants.Bundles.IronTools)),
    AllStoneTools(MultiItemInInventoryListenerBuilder(Constants.Bundles.StoneTools)),
    AllTypesOfDoorsIncludingTrapdoors(MultiItemInInventoryListenerBuilder(Constants.Bundles.Doors)),
    AllWoodTools(MultiItemInInventoryListenerBuilder(Constants.Bundles.WoodTools)),
    AnyChainArmor,
    AnyConcreteBlock(MultiItemInInventoryListenerBuilder(Constants.Bundles.ConcreteBlocks, UniqueCount.Any)),
    AnyGlazedTerracotta(
        MultiItemInInventoryListenerBuilder(
            Constants.Bundles.GlazedTerracottaBlocks,
            UniqueCount.Any
        )
    ),
    AnyTippedArrow,
    BarterWithPiglin,
    BlowUpBedInNether,
    BounceOnSlimeBlock,
    BreakDiamondTool,
    BreakPieceOfDiamondArmor,
    BreakShield,
    BreakAnyArmor,
    BreakAnyTool,
    BreedAxolotl(BreedListenerBuilder(EntityType.AXOLOTL)),
    BreedBee(BreedListenerBuilder(EntityType.BEE)),
    BreedCat(BreedListenerBuilder(EntityType.CAT)),
    BreedChicken(BreedListenerBuilder(EntityType.CHICKEN)),
    BreedCow(BreedListenerBuilder(EntityType.COW)),
    BreedDonkey(BreedListenerBuilder(EntityType.DONKEY)),
    BreedFox(BreedListenerBuilder(EntityType.FOX)),
    BreedGoat(BreedListenerBuilder(EntityType.GOAT)),
    BreedHoglin(BreedListenerBuilder(EntityType.HOGLIN)),
    BreedHorse(BreedListenerBuilder(EntityType.HORSE)),
    BreedLlama(BreedListenerBuilder(EntityType.LLAMA)),
    BreedMule(BreedListenerBuilder(EntityType.MULE)),
    BreedOcelot(BreedListenerBuilder(EntityType.OCELOT)),
    BreedPanda(BreedListenerBuilder(EntityType.PANDA)),
    BreedPig(BreedListenerBuilder(EntityType.PIG)),
    BreedRabbit(BreedListenerBuilder(EntityType.RABBIT)),
    BreedSheep(BreedListenerBuilder(EntityType.SHEEP)),
    BreedStrider(BreedListenerBuilder(EntityType.STRIDER)),
    BreedTurtle,
    BreedWolf(BreedListenerBuilder(EntityType.WOLF)),
    BrewPotionOfFireResistance(BrewListenerBuilder(PotionType.FIRE_RESISTANCE)),
    BrewPotionOfHarming(BrewListenerBuilder(PotionType.INSTANT_DAMAGE)),
    BrewPotionOfHealing(BrewListenerBuilder(PotionType.INSTANT_HEAL)),
    BrewPotionOfInvisibility(BrewListenerBuilder(PotionType.INVISIBILITY)),
    BrewPotionOfLeaping(BrewListenerBuilder(PotionType.JUMP)),
    BrewPotionOfNightVision(BrewListenerBuilder(PotionType.NIGHT_VISION)),
    BrewPotionOfRegeneration(BrewListenerBuilder(PotionType.REGEN)),
    BrewPotionOfSlowness(BrewListenerBuilder(PotionType.SLOWNESS)),
    BrewPotionOfStrength(BrewListenerBuilder(PotionType.STRENGTH)),
    BrewPotionOfSwiftness(BrewListenerBuilder(PotionType.SPEED)),
    BrewPotionOfWaterBreathing(BrewListenerBuilder(PotionType.WATER_BREATHING)),
    BrewPotionOfWeakness(BrewListenerBuilder(PotionType.WEAKNESS)),
    BrewAnyLingeringPotion,
    CarvePumpkin,
    CleanBannerWithCauldron(CleanBannerListenerBuilder()),
    CompleteMap,
    Cook4FoodOnCampfire,
    CraftActivatorRail(CraftListenerBuilder(Material.ACTIVATOR_RAIL)),
    CraftAnvil(CraftListenerBuilder(Material.ANVIL)),
    CraftArmorStand(CraftListenerBuilder(Material.ARMOR_STAND)),
    CraftBeehive(CraftListenerBuilder(Material.BEEHIVE)),
    CraftBlastFurnace(CraftListenerBuilder(Material.BLAST_FURNACE)),
    CraftBookshelf(CraftListenerBuilder(Material.BOOKSHELF)),
    CraftCake(CraftListenerBuilder(Material.CAKE)),
    CraftCampfire(CraftListenerBuilder(Material.CAMPFIRE)),
    CraftCandle(CraftListenerBuilder(Material.CANDLE)),
    CraftCartographyTable(CraftListenerBuilder(Material.CARTOGRAPHY_TABLE)),
    CraftClock(CraftListenerBuilder(Material.CLOCK)),
    CraftCompass(CraftListenerBuilder(Material.COMPASS)),
    CraftDaylightDetector(CraftListenerBuilder(Material.DAYLIGHT_DETECTOR)),
    CraftDispenser(CraftListenerBuilder(Material.DISPENSER)),
    CraftDropper(CraftListenerBuilder(Material.DROPPER)),
    CraftEndCrystal(CraftListenerBuilder(Material.END_CRYSTAL)),
    CraftEnderChest(CraftListenerBuilder(Material.ENDER_CHEST)),
    CraftFireCharge(CraftListenerBuilder(Material.FIRE_CHARGE)),
    CraftFletchingTable(CraftListenerBuilder(Material.FLETCHING_TABLE)),
    CraftGrindstone(CraftListenerBuilder(Material.GRINDSTONE)),
    CraftHoneyBlock(CraftListenerBuilder(Material.HONEY_BLOCK)),
    CraftHopper(CraftListenerBuilder(Material.HOPPER)),
    CraftJackOlantern(CraftListenerBuilder(Material.JACK_O_LANTERN)),
    CraftJukebox(CraftListenerBuilder(Material.JUKEBOX)),
    CraftLectern(CraftListenerBuilder(Material.LECTERN)),
    CraftLoom(CraftListenerBuilder(Material.LOOM)),
    CraftMagmaCream(CraftListenerBuilder(Material.MAGMA_CREAM)),
    CraftNoteBlock(CraftListenerBuilder(Material.NOTE_BLOCK)),
    CraftObserver(CraftListenerBuilder(Material.OBSERVER)),
    CraftPainting(CraftListenerBuilder(Material.PAINTING)),
    CraftPiston(CraftListenerBuilder(Material.PISTON)),
    CraftPoweredRail(CraftListenerBuilder(Material.POWERED_RAIL)),
    CraftPrismarineBrick(CraftListenerBuilder(Material.PRISMARINE_BRICKS)),
    CraftRabbitStew(CraftListenerBuilder(Material.RABBIT_STEW)),
    CraftRedNetherBrick(CraftListenerBuilder(Material.RED_NETHER_BRICKS)),
    CraftRedstoneComparator(CraftListenerBuilder(Material.COMPARATOR)),
    CraftRedstoneLamp(CraftListenerBuilder(Material.REDSTONE_LAMP)),
    CraftRedstoneRepeater(CraftListenerBuilder(Material.REPEATER)),
    CraftRespawnAnchor(CraftListenerBuilder(Material.RESPAWN_ANCHOR)),
    CraftScaffolding(CraftListenerBuilder(Material.SCAFFOLDING)),
    CraftSmoker(CraftListenerBuilder(Material.SMOKER)),
    CraftSoulCampfire(CraftListenerBuilder(Material.SOUL_CAMPFIRE)),
    CraftSoulLantern(CraftListenerBuilder(Material.SOUL_LANTERN)),
    CraftSpyglass(CraftListenerBuilder(Material.SPYGLASS)),
    CraftStickyPiston(CraftListenerBuilder(Material.STICKY_PISTON)),
    CraftStonecutter(CraftListenerBuilder(Material.STONECUTTER)),
    CraftTarget(CraftListenerBuilder(Material.TARGET)),
    CraftTrappedChest(CraftListenerBuilder(Material.TRAPPED_CHEST)),
    CreateDirtPathBlock,
    DestroyMobSpawner,
    Die(PlayerDeathListenerBuilder()),
    DrinkHoneyBottle(ConsumeListenerBuilder(Material.HONEY_BOTTLE)),
    DrinkMilk(ConsumeListenerBuilder(Material.MILK_BUCKET)),
    DrySponge,
    DyeLeatherArmorPiece,
    DyeSheep,
    EatApple(ConsumeListenerBuilder(Material.APPLE)),
    EatBakedPotato(ConsumeListenerBuilder(Material.BAKED_POTATO)),
    EatBeetroot(ConsumeListenerBuilder(Material.BEETROOT)),
    EatBeetrootSoup(ConsumeListenerBuilder(Material.BEETROOT_SOUP)),
    EatBread(ConsumeListenerBuilder(Material.BREAD)),
    EatCarrot(ConsumeListenerBuilder(Material.CARROT)),
    EatChorusFruit(ConsumeListenerBuilder(Material.CHORUS_FRUIT)),
    EatCookedBeef(ConsumeListenerBuilder(Material.COOKED_BEEF)),
    EatCookedChicken(ConsumeListenerBuilder(Material.COOKED_CHICKEN)),
    EatCookedCod(ConsumeListenerBuilder(Material.COOKED_COD)),
    EatCookedMutton(ConsumeListenerBuilder(Material.COOKED_MUTTON)),
    EatCookedPorkchop(ConsumeListenerBuilder(Material.COOKED_PORKCHOP)),
    EatCookedRabbit(ConsumeListenerBuilder(Material.COOKED_RABBIT)),
    EatCookedSalmon(ConsumeListenerBuilder(Material.COOKED_SALMON)),
    EatCookie(ConsumeListenerBuilder(Material.COOKIE)),
    EatDriedKelp(ConsumeListenerBuilder(Material.DRIED_KELP)),
    EatEnchantedGoldenApple(ConsumeListenerBuilder(Material.ENCHANTED_GOLDEN_APPLE)),
    EatGlowBerry(ConsumeListenerBuilder(Material.GLOW_BERRIES)),
    EatGoldenApple(ConsumeListenerBuilder(Material.GOLDEN_APPLE)),
    EatGoldenCarrot(ConsumeListenerBuilder(Material.GOLDEN_CARROT)),
    EatMelonSlice(ConsumeListenerBuilder(Material.MELON_SLICE)),
    EatMushroomStew(ConsumeListenerBuilder(Material.MUSHROOM_STEW)),
    EatPoisonPotato(ConsumeListenerBuilder(Material.POISONOUS_POTATO)),
    EatPotato(ConsumeListenerBuilder(Material.POTATO)),
    EatPufferfish(ConsumeListenerBuilder(Material.PUFFERFISH)),
    EatPumpkinPie(ConsumeListenerBuilder(Material.PUMPKIN_PIE)),
    EatRabbitStew(ConsumeListenerBuilder(Material.RABBIT_STEW)),
    EatRawBeef(ConsumeListenerBuilder(Material.BEEF)),
    EatRawChicken(ConsumeListenerBuilder(Material.CHICKEN)),
    EatRawCod(ConsumeListenerBuilder(Material.COD)),
    EatRawMutton(ConsumeListenerBuilder(Material.MUTTON)),
    EatRawPorkchop(ConsumeListenerBuilder(Material.PORKCHOP)),
    EatRawRabbit(ConsumeListenerBuilder(Material.RABBIT)),
    EatRawSalmon(ConsumeListenerBuilder(Material.SALMON)),
    EatRottenFlesh(ConsumeListenerBuilder(Material.ROTTEN_FLESH)),
    EatSpiderEye(ConsumeListenerBuilder(Material.SPIDER_EYE)),
    EatSuspiciousStew(ConsumeListenerBuilder(Material.SUSPICIOUS_STEW)),
    EatSweetBerry(ConsumeListenerBuilder(Material.SWEET_BERRIES)),
    EatTropicalFish(ConsumeListenerBuilder(Material.TROPICAL_FISH)),
    EnchantBook(EnchantListenerBuilder(Material.BOOK)),
    EnchantFishingPole(EnchantListenerBuilder(Material.FISHING_ROD)),
    EnchantWoodenTool,
    EnterBadlandsBiome,
    EnterBambooJungleBiome,
    EnterDesertTemple(EnterStructureListenerBuilder(StructureType.DESERT_PYRAMID)),
    EnterDesertVillage(EnterStructureListenerBuilder(VillageType.DesertVillage)),
    EnterDungeon,
    EnterEndCity(EnterStructureListenerBuilder(StructureType.END_CITY)),
    EnterIceSpikesBiome,
    EnterIgloo(EnterStructureListenerBuilder(StructureType.IGLOO)),
    EnterJungleBiome,
    EnterJungleTemple(EnterStructureListenerBuilder(StructureType.JUNGLE_PYRAMID)),
    EnterLargeTreeTaigaBiome,
    EnterMushroomIslandBiome,
    EnterPlainsVillage(EnterStructureListenerBuilder(VillageType.PlainsVillage)),
    EnterRavine,
    EnterSavannaVillage(EnterStructureListenerBuilder(VillageType.SavannaVillage)),
    EnterShatteredSavannaBiome,
    EnterShipwreck(EnterStructureListenerBuilder(StructureType.SHIPWRECK)),
    EnterTaigaVillage(EnterStructureListenerBuilder(VillageType.TaigaVillage)),
    EnterTundraBiome,
    EnterTundraVillage(EnterStructureListenerBuilder(VillageType.SnowyVillage)),
    EnterWarmOceanBiome,
    EnterWitchHut(EnterStructureListenerBuilder(StructureType.SWAMP_HUT)),
    EnterAmethystGeode,
    EquipCurseOfBindingItem,
    FeedWheatToHorse,
    FillComposter,
    FullDiamondArmor,
    FullGoldArmor,
    FullIronArmor,
    FullLeatherArmor,
    FullNetheriteArmor,
    GetSkeletonToShootSkeleton,
    GetAbsorptionEffect(PotionEffectListenerBuilder(PotionEffectType.ABSORPTION)),
    GetBlindnessEffect(PotionEffectListenerBuilder(PotionEffectType.BLINDNESS)),
    GetDolphinsGraceEffect(PotionEffectListenerBuilder(PotionEffectType.DOLPHINS_GRACE)),
    GetGlowingEffect(PotionEffectListenerBuilder(PotionEffectType.GLOWING)),
    GetHungerEffect(PotionEffectListenerBuilder(PotionEffectType.HUNGER)),
    GetLevitationEffect(PotionEffectListenerBuilder(PotionEffectType.LEVITATION)),
    GetMiningFatigueEffect(PotionEffectListenerBuilder(PotionEffectType.SLOW_DIGGING)),
    GetRegenerationEffect(PotionEffectListenerBuilder(PotionEffectType.REGENERATION)),
    GetResistanceEffect(PotionEffectListenerBuilder(PotionEffectType.DAMAGE_RESISTANCE)),
    GetWitherEffect(PotionEffectListenerBuilder(PotionEffectType.WITHER)),
    GrowDarkOakTree(StructureGrowListenerBuilder(TreeType.DARK_OAK)),
    GrowGiantMushroom,
    GrowLargeJungleTree(StructureGrowListenerBuilder(TreeType.JUNGLE)),
    GrowLargeSpruceTree(StructureGrowListenerBuilder(TreeType.MEGA_REDWOOD)),
    HaveDolphinLeadYouToTreasure,
    HitYourselfWithArrow,
    KillAxolotl(KillListenerBuilder(EntityType.AXOLOTL)),
    KillBabyVillager,
    KillBabyZombieWithArrow,
    KillBat(KillListenerBuilder(EntityType.BAT)),
    KillBee(KillListenerBuilder(EntityType.BEE)),
    KillBlaze(KillListenerBuilder(EntityType.BLAZE)),
    KillBlazeWithSnowballs,
    KillCat(KillListenerBuilder(EntityType.CAT)),
    KillCaveSpider(KillListenerBuilder(EntityType.CAVE_SPIDER)),
    KillChicken(KillListenerBuilder(EntityType.CHICKEN)),
    KillCod(KillListenerBuilder(EntityType.COD)),
    KillCow(KillListenerBuilder(EntityType.COW)),
    KillCreeper(KillListenerBuilder(EntityType.CREEPER)),
    KillCreeperWithAnotherCreeper,
    KillCreeperWithTnt,
    KillDolphin(KillListenerBuilder(EntityType.DOLPHIN)),
    KillDonkey(KillListenerBuilder(EntityType.DONKEY)),
    KillDrowned(KillListenerBuilder(EntityType.DROWNED)),
    KillDrownedHoldingTrident,
    KillElderGuardian(KillListenerBuilder(EntityType.ELDER_GUARDIAN)),
    KillEnderDragon(KillListenerBuilder(EntityType.ENDER_DRAGON)),
    KillEnderDragonWithoutBeds,
    KillEnderman(KillListenerBuilder(EntityType.ENDERMAN)),
    KillEndermite(KillListenerBuilder(EntityType.ENDERMITE)),
    KillEvoker(KillListenerBuilder(EntityType.EVOKER)),
    KillFox(KillListenerBuilder(EntityType.FOX)),
    KillGhast(KillListenerBuilder(EntityType.GHAST)),
    KillGlowSquid(KillListenerBuilder(EntityType.GLOW_SQUID)),
    KillGuardian(KillListenerBuilder(EntityType.GUARDIAN)),
    KillHoglin(KillListenerBuilder(EntityType.HOGLIN)),
    KillHorse(KillListenerBuilder(EntityType.HORSE)),
    KillHusk(KillListenerBuilder(EntityType.HUSK)),
    KillIronGolem(KillListenerBuilder(EntityType.IRON_GOLEM)),
    KillLlama(KillListenerBuilder(EntityType.LLAMA)),
    KillMagmaCube(KillListenerBuilder(EntityType.MAGMA_CUBE)),
    KillMobWhileItsOnFire,
    KillMobWithTamedWolf,
    KillMobWithDripstone,
    KillMobWithFallDamage,
    KillMooshroom(KillListenerBuilder(EntityType.MUSHROOM_COW)),
    KillMule(KillListenerBuilder(EntityType.MULE)),
    KillOcelot(KillListenerBuilder(EntityType.OCELOT)),
    KillPanda(KillListenerBuilder(EntityType.PANDA)),
    KillParrot(KillListenerBuilder(EntityType.PARROT)),
    KillPhantom(KillListenerBuilder(EntityType.PHANTOM)),
    KillPig(KillListenerBuilder(EntityType.PIG)),
    KillPiglin(KillListenerBuilder(EntityType.PIGLIN)),
    KillPiglinBrute(KillListenerBuilder(EntityType.PIGLIN_BRUTE)),
    KillPillager(KillListenerBuilder(EntityType.PILLAGER)),
    KillPolarBear(KillListenerBuilder(EntityType.POLAR_BEAR)),
    KillPufferfish(KillListenerBuilder(EntityType.PUFFERFISH)),
    KillRabbit(KillListenerBuilder(EntityType.RABBIT)),
    KillRavager(KillListenerBuilder(EntityType.RAVAGER)),
    KillSalmon(KillListenerBuilder(EntityType.SALMON)),
    KillSheep(KillListenerBuilder(EntityType.SHEEP)),
    KillShulker(KillListenerBuilder(EntityType.SHULKER)),
    KillSilverfish(KillListenerBuilder(EntityType.SILVERFISH)),
    KillSkeleton(KillListenerBuilder(EntityType.SKELETON)),
    KillSkeletonWithoutItDamagingYou,
    KillSlime(KillListenerBuilder(EntityType.SLIME)),
    KillSnowGolem(KillListenerBuilder(EntityType.SNOWMAN)),
    KillSpider(KillListenerBuilder(EntityType.SPIDER)),
    KillSpiderJockey,
    KillSquid(KillListenerBuilder(EntityType.SQUID)),
    KillStray(KillListenerBuilder(EntityType.STRAY)),
    KillStrider(KillListenerBuilder(EntityType.STRIDER)),
    KillTropicalFish(KillListenerBuilder(EntityType.TROPICAL_FISH)),
    KillTurtle(KillListenerBuilder(EntityType.TURTLE)),
    KillVex(KillListenerBuilder(EntityType.VEX)),
    KillVillager(KillListenerBuilder(EntityType.VILLAGER)),
    KillVindicator(KillListenerBuilder(EntityType.VINDICATOR)),
    KillWitch(KillListenerBuilder(EntityType.WITCH)),
    KillWither(KillListenerBuilder(EntityType.WITHER)),
    KillWitherSkeleton(KillListenerBuilder(EntityType.WITHER_SKELETON)),
    KillWolf(KillListenerBuilder(EntityType.WOLF)),
    KillZoglin(KillListenerBuilder(EntityType.ZOGLIN)),
    KillZombie(KillListenerBuilder(EntityType.ZOMBIE)),
    KillZombiePiglin(KillListenerBuilder(EntityType.ZOMBIFIED_PIGLIN)),
    KillZombieVillager(KillListenerBuilder(EntityType.ZOMBIE_VILLAGER)),
    LightCreeperWithFlintSteel,
    LightTntWithFlintSteel,
    LightTntWithRedstone,
    LootBuriedTreasure(LootableListenerBuilder(StructureType.BURIED_TREASURE)),
    LootRuinedPortalChest(LootableListenerBuilder(StructureType.RUINED_PORTAL)),
    MakeEfficiency5Tool(PlayerUpdateEnchantmentListenerBuilder(Enchantment.DIG_SPEED, 5)),
    MakePower5Bow(PlayerUpdateEnchantmentListenerBuilder(Enchantment.ARROW_DAMAGE, 5)),
    MakeSharpness5Sword(PlayerUpdateEnchantmentListenerBuilder(Enchantment.DAMAGE_ALL, 5)),
    MakeWitchPoisonItself,
    MineAncientDebris(BlockBreakListenerBuilder(Material.ANCIENT_DEBRIS)),
    MineCoalOre(BlockBreakListenerBuilder(Material.COAL_ORE)),
    MineCopperOre(BlockBreakListenerBuilder(Material.COPPER_ORE)),
    MineDiamondOre(BlockBreakListenerBuilder(Material.DIAMOND_ORE)),
    MineEmeraldOre(BlockBreakListenerBuilder(Material.EMERALD_ORE)),
    MineGoldOre(BlockBreakListenerBuilder(Material.GOLD_ORE)),
    MineIronOre(BlockBreakListenerBuilder(Material.IRON_ORE)),
    MineLapisLazuliOre(BlockBreakListenerBuilder(Material.LAPIS_ORE)),
    MineNetherGoldOre(BlockBreakListenerBuilder(Material.NETHER_GOLD_ORE)),
    MineNetherQuartzOre(BlockBreakListenerBuilder(Material.NETHER_QUARTZ_ORE)),
    MineRedstoneOre(BlockBreakListenerBuilder(Material.REDSTONE_ORE)),
    Obtain12UniqueFlowers(MultiItemInInventoryListenerBuilder(Constants.Bundles.Flowers, 12)),
    ObtainAmethystShard(ItemInInventoryListenerBuilder(Material.AMETHYST_SHARD)),
    ObtainMendingBook,
    ObtainNameTag(ItemInInventoryListenerBuilder(Material.NAME_TAG)),
    ObtainNautilusShell(ItemInInventoryListenerBuilder(Material.NAUTILUS_SHELL)),
    ObtainSaddle(ItemInInventoryListenerBuilder(Material.SADDLE)),
    ObtainTrident(ItemInInventoryListenerBuilder(Material.TRIDENT)),
    ObtainAnyMobHead(MultiItemInInventoryListenerBuilder(Constants.Bundles.MobHeads, UniqueCount.Any)),
    ObtainDiamondHorseArmor(ItemInInventoryListenerBuilder(Material.DIAMOND_HORSE_ARMOR)),
    ObtainGoldHorseArmor(ItemInInventoryListenerBuilder(Material.GOLDEN_HORSE_ARMOR)),
    ObtainIronHorseArmor(ItemInInventoryListenerBuilder(Material.IRON_HORSE_ARMOR)),
    ObtainLeatherHorseArmor(ItemInInventoryListenerBuilder(Material.LEATHER_HORSE_ARMOR)),
    PlantBamboo(BlockPlaceListenerBuilder(Material.BAMBOO_SAPLING)),
    PlantBeetrootSeed(BlockPlaceListenerBuilder(Material.BEETROOTS)),
    PlantChorusFruit(BlockPlaceListenerBuilder(Material.CHORUS_PLANT)),
    PlantCocoaBean(BlockPlaceListenerBuilder(Material.COCOA)),
    PlantNetherWart(BlockPlaceListenerBuilder(Material.NETHER_WART)),
    PlantPumpkinSeed(BlockPlaceListenerBuilder(Material.PUMPKIN_STEM)),
    PlantSugarCane(BlockPlaceListenerBuilder(Material.SUGAR_CANE)),
    PlantWheatSeed(BlockPlaceListenerBuilder(Material.WHEAT_SEEDS)),
    PlantAnySapling,
    PlantSomethingInFlowerPot,
    PlayMusicDisc,
    PushMobWithPiston,
    ReachLevel10(LevelChangeListenerBuilder(10)),
    ReachLevel25(LevelChangeListenerBuilder(25)),
    ReachBuildLimitY256,
    ReachY0InEnd,
    RepairToolInAnvil,
    RideBoatWithCreeper,
    RideMinecartOnRail,
    RidePig,
    RingBell,
    SetYourSpawnWithBed,
    ShearMooshroom,
    ShearSheep,
    ShootBatWithArrow,
    ShootBell,
    ShootFireworkFromCrossbow,
    StandOnBedrock,
    StareAtSunWithSpyglass,
    StripLog,
    SwimInDesertWell,
    SwimInLavaWithFireResistance,
    TameCat(TameListenerBuilder(EntityType.CAT)),
    TameDonkey(TameListenerBuilder(EntityType.DONKEY)),
    TameHorse(TameListenerBuilder(EntityType.HORSE)),
    TameLlama(TameListenerBuilder(EntityType.LLAMA)),
    TameMule(TameListenerBuilder(EntityType.MULE)),
    TameParrot(TameListenerBuilder(EntityType.PARROT)),
    TameWolf(TameListenerBuilder(EntityType.WOLF)),
    ThrowDiamondInLava,
    ThrowEnderPearl(ProjectileLaunchListenerBuilder(EntityType.ENDER_PEARL)),
    ThrowSnowball(ProjectileLaunchListenerBuilder(EntityType.SNOWBALL)),
    ThrowEgg,
    TrapMobInBoat,
    UseAnyDyeOnSign,
    UseBonemealOnGrass,
    WearCarvedPumpkin,
    WriteBook,
    Unknown;

    fun addListener(state: State, player: Player): Listener? {
        if (builder is ObjectiveListenerBuilder) {
            val factory = builder.createFactory()
            return factory.registerEvent(builder.eventClass(), state, this, player)
        }
        return null
    }
}
