package util

import game.State
import listener.*
import org.bukkit.Bukkit
import org.bukkit.Material
import org.bukkit.entity.Player
import org.bukkit.StructureType
import org.bukkit.TreeType
import org.bukkit.enchantments.Enchantment
import org.bukkit.entity.*
import org.bukkit.event.Listener
import org.bukkit.loot.LootTables
import org.bukkit.potion.PotionEffectType
import org.bukkit.potion.PotionType

enum class Objective(val listenerFactory: (State, Objective, Player) -> Listener = noop) {
    ACompleteCatalogueAdvancement(AdvancementListener.factory("husbandry/complete_catalogue")),
    AFuriousCocktailAdvancement(AdvancementListener.factory("nether/all_potions")),
    ASeedyPlaceAdvancement(AdvancementListener.factory("husbandry/plant_seed")),
    ATerribleFortressAdvancement(AdvancementListener.factory("nether/find_fortress")),
    AcquireHardwareAdvancement(AdvancementListener.factory("story/smelt_iron")),
    ArbalisticAdvancement(AdvancementListener.factory("adventure/arbalistic")),
    BeeOurGuestAdvancement(AdvancementListener.factory("husbandry/safely_harvest_honey")),
    BestFriendsForeverAdvancement(AdvancementListener.factory("husbandry/tame_an_animal")),
    BullseyeAdvancement(AdvancementListener.factory("adventure/bullseye")),
    CountryLodeTakeMeHomeAdvancement(AdvancementListener.factory("nether/use_lodestone")),
    CoverMeWithDiamondsAdvancement(AdvancementListener.factory("story/shiny_gear")),
    DiamondsAdvancement(AdvancementListener.factory("story/mine_diamond")),
    EnchanterAdvancement(AdvancementListener.factory("story/enchant_item")),
    FishyBusinessAdvancement(AdvancementListener.factory("husbandry/fishy_business")),
    GettingAnUpgradeAdvancement(AdvancementListener.factory("story/upgrade_tools")),
    GlowAndBeholdAdvancement(AdvancementListener.factory("husbandry/make_a_sign_glow")),
    GreatViewFromUpHereAdvancement(AdvancementListener.factory("end/levitate")),
    HeroOfTheVillageAdvancement(AdvancementListener.factory("adventure/hero_of_the_village")),
    HiddenInTheDepthsAdvancement(AdvancementListener.factory("nether/obtain_ancient_debris")),
    HiredHelpAdvancement(AdvancementListener.factory("adventure/summon_iron_golem")),
    HotStuffAdvancement(AdvancementListener.factory("story/lava_bucket")),
    HotTouristDestinationsAdvancement(AdvancementListener.factory("nether/explore_nether")),
    IceBucketChallengeAdvancement(AdvancementListener.factory("story/form_obsidian")),
    IntoFireAdvancement(AdvancementListener.factory("nether/obtain_blaze_rod")),
    IsItABalloonAdvancement(AdvancementListener.factory("adventure/spyglass_at_ghast")),
    IsItAPlaneAdvancement(AdvancementListener.factory("adventure/spyglass_at_dragon")),
    IsntItIronPickAdvancement(AdvancementListener.factory("story/iron_tools")),
    IsItABirdAdvancement(AdvancementListener.factory("adventure/spyglass_at_parrot")),
    LocalBreweryAdvancement(AdvancementListener.factory("nether/brew_potion")),
    MonsterHunterAdvancement(AdvancementListener.factory("adventure/kill_a_mob")),
    NotQuiteNineLivesAdvancement(AdvancementListener.factory("nether/charge_respawn_anchor")),
    NotTodayThankYouAdvancement(AdvancementListener.factory("story/deflect_arrow")),
    OhShinyAdvancement(AdvancementListener.factory("nether/distract_piglin")),
    OlBetsyAdvancement(AdvancementListener.factory("adventure/ol_betsy")),
    PostmortalAdvancement(AdvancementListener.factory("adventure/totem_of_undying")),
    RemoteGetawayAdvancement(AdvancementListener.factory("end/enter_end_gateway")),
    ReturnToSenderAdvancement(AdvancementListener.factory("nether/return_to_sender")),
    SeriousDedicationAdvancement(AdvancementListener.factory("husbandry/obtain_netherite_hoe")),
    SkysTheLimitAdvancement(AdvancementListener.factory("end/elytra")),
    SniperDuelAdvancement(AdvancementListener.factory("adventure/sniper_duel")),
    SpookyScarySkeletonAdvancement(AdvancementListener.factory("nether/get_wither_skull")),
    StickySituationAdvancement(AdvancementListener.factory("adventure/honey_block_slide")),
    StoneAgeAdvancement(AdvancementListener.factory("story/mine_stone")),
    SubspaceBubbleAdvancement(AdvancementListener.factory("nether/fast_travel")),
    SuitUpAdvancement(AdvancementListener.factory("story/obtain_armor")),
    SweetDreamsAdvancement(AdvancementListener.factory("adventure/sleep_in_bed")),
    TacticalFishingAdvancement(AdvancementListener.factory("husbandry/tactical_fishing")),
    TakeAimAdvancement(AdvancementListener.factory("adventure/shoot_arrow")),
    TheCutestPredatorAdvancement(AdvancementListener.factory("husbandry/axolotl_in_a_bucket")),
    TheEndAdvancement(AdvancementListener.factory("end/root")),
    TheEndAgainAdvancement(AdvancementListener.factory("end/respawn_dragon")),
    TheHealingPowerOfFriendshipAdvancement(AdvancementListener.factory("husbandry/kill_axolotl_target")),
    TheNextGenerationAdvancement(AdvancementListener.factory("end/dragon_egg")),
    TheParrotsAndTheBatsAdvancement(AdvancementListener.factory("husbandry/breed_an_animal")),
    ThisBoatHasLegsAdvancement(AdvancementListener.factory("nether/ride_strider")),
    ThoseWereTheDaysAdvancement(AdvancementListener.factory("nether/find_bastion")),
    TotalBeelocationAdvancement(AdvancementListener.factory("husbandry/silk_touch_nest")),
    TwoBirdsOneArrowAdvancement(AdvancementListener.factory("adventure/two_birds_one_arrow")),
    UneasyAllianceAdvancement(AdvancementListener.factory("nether/uneasy_alliance")),
    VoluntaryExileAdvancement(AdvancementListener.factory("adventure/voluntary_exile")),
    WarPigsAdvancement(AdvancementListener.factory("nether/loot_bastion")),
    WaxOffAdvancement(AdvancementListener.factory("husbandry/wax_off")),
    WaxOnAdvancement(AdvancementListener.factory("husbandry/wax_on")),
    WeNeedToGoDeeperAdvancement(AdvancementListener.factory("story/enter_the_nether")),
    WhatADealAdvancement(AdvancementListener.factory("adventure/trade")),
    WhateverFloatsYourGoatAdvancement(AdvancementListener.factory("husbandry/ride_a_boat_with_a_goat")),
    WhoIsCuttingOnionsAdvancement(AdvancementListener.factory("nether/obtain_crying_obsidian")),
    WhosThePillagerNowAdvancement(AdvancementListener.factory("adventure/whos_the_pillager_now")),
    WitheringHeightsAdvancement(AdvancementListener.factory("nether/summon_wither")),
    YouNeedAMintAdvancement(AdvancementListener.factory("end/dragon_breath")),
    ZombieDoctorAdvancement(AdvancementListener.factory("story/cure_zombie_villager")),
    UniqueConcreteBlocks12(MultiItemInInventoryListener.factory(Constants.Bundles.ConcreteBlocks, 12)),
    BlackStainedGlass16(ItemInInventoryListener.factory(Material.BLACK_STAINED_GLASS, 16)),
    BlackWool16(ItemInInventoryListener.factory(Material.BLACK_WOOL, 16)),
    BlueIce16(ItemInInventoryListener.factory(Material.BLUE_ICE, 16)),
    BlueStainedGlass16(ItemInInventoryListener.factory(Material.BLUE_STAINED_GLASS, 16)),
    BlueWool16(ItemInInventoryListener.factory(Material.BLUE_WOOL, 16)),
    BrownStainedGlass16(ItemInInventoryListener.factory(Material.BROWN_STAINED_GLASS, 16)),
    BrownWool16(ItemInInventoryListener.factory(Material.BROWN_WOOL, 16)),
    CyanStainedGlass16(ItemInInventoryListener.factory(Material.CYAN_STAINED_GLASS, 16)),
    CyanWool16(ItemInInventoryListener.factory(Material.CYAN_WOOL, 16)),
    Eggs16(ItemInInventoryListener.factory(Material.EGG, 16)),
    EnderPearls16(ItemInInventoryListener.factory(Material.ENDER_PEARL, 16)),
    GrassBlocks16(ItemInInventoryListener.factory(Material.GRASS_BLOCK, 16)),
    GrayStainedGlass16(ItemInInventoryListener.factory(Material.GRAY_STAINED_GLASS, 16)),
    GrayWool16(ItemInInventoryListener.factory(Material.GRAY_WOOL, 16)),
    GreenStainedGlass16(ItemInInventoryListener.factory(Material.GREEN_STAINED_GLASS, 16)),
    GreenWool16(ItemInInventoryListener.factory(Material.GREEN_WOOL, 16)),
    InkSacks16(ItemInInventoryListener.factory(Material.INK_SAC, 16)),
    LightBlueStainedGlass16(ItemInInventoryListener.factory(Material.LIGHT_BLUE_STAINED_GLASS, 16)),
    LightBlueWool16(ItemInInventoryListener.factory(Material.LIGHT_BLUE_WOOL, 16)),
    LightGrayStainedGlass16(ItemInInventoryListener.factory(Material.LIGHT_GRAY_STAINED_GLASS, 16)),
    LightGrayWool16(ItemInInventoryListener.factory(Material.LIGHT_GRAY_WOOL, 16)),
    LimeGreenStainedGlass16(ItemInInventoryListener.factory(Material.LIME_STAINED_GLASS, 16)),
    LimeGreenWool16(ItemInInventoryListener.factory(Material.LIME_WOOL, 16)),
    MagentaStainedGlass16(ItemInInventoryListener.factory(Material.MAGENTA_STAINED_GLASS, 16)),
    MagentaWool16(ItemInInventoryListener.factory(Material.MAGENTA_WOOL, 16)),
    OrangeStainedGlass16(ItemInInventoryListener.factory(Material.ORANGE_STAINED_GLASS, 16)),
    OrangeWool16(ItemInInventoryListener.factory(Material.ORANGE_WOOL, 16)),
    PinkStainedGlass16(ItemInInventoryListener.factory(Material.PINK_STAINED_GLASS, 16)),
    PinkWool16(ItemInInventoryListener.factory(Material.PINK_WOOL, 16)),
    Podzol16(ItemInInventoryListener.factory(Material.PODZOL, 16)),
    Pumpkins16(ItemInInventoryListener.factory(Material.PUMPKIN, 16)),
    PurpleStainedGlass16(ItemInInventoryListener.factory(Material.PURPLE_STAINED_GLASS, 16)),
    PurpleWool16(ItemInInventoryListener.factory(Material.PURPLE_WOOL, 16)),
    RedStainedGlass16(ItemInInventoryListener.factory(Material.RED_STAINED_GLASS, 16)),
    RedWool16(ItemInInventoryListener.factory(Material.RED_WOOL, 16)),
    TintedGlass16(ItemInInventoryListener.factory(Material.TINTED_GLASS, 16)),
    WhiteStainedGlass16(ItemInInventoryListener.factory(Material.WHITE_STAINED_GLASS, 16)),
    WhiteWool16(ItemInInventoryListener.factory(Material.WHITE_WOOL, 16)),
    YellowStainedGlass16(ItemInInventoryListener.factory(Material.YELLOW_STAINED_GLASS, 16)),
    YellowWool16(ItemInInventoryListener.factory(Material.YELLOW_WOOL, 16)),
    UniqueConcreteBlocks3(MultiItemInInventoryListener.factory(Constants.Bundles.ConcreteBlocks, 3)),
    BlazeRods32(ItemInInventoryListener.factory(Material.BLAZE_ROD, 32)),
    Diamonds32(ItemInInventoryListener.factory(Material.DIAMOND, 32)),
    SpiderEyes32(ItemInInventoryListener.factory(Material.SPIDER_EYE, 32)),
    AcaciaLogs64(ItemInInventoryListener.factory(Material.ACACIA_LOG, 64)),
    AmethystShards64(ItemInInventoryListener.factory(Material.AMETHYST_SHARD, 64)),
    Andesite64(ItemInInventoryListener.factory(Material.ANDESITE, 64)),
    Apples64(ItemInInventoryListener.factory(Material.APPLE, 64)),
    Arrows64(ItemInInventoryListener.factory(Material.ARROW, 64)),
    BirchLogs64(ItemInInventoryListener.factory(Material.BIRCH_LOG, 64)),
    Bones64(ItemInInventoryListener.factory(Material.BONE, 64)),
    Cacti64(ItemInInventoryListener.factory(Material.CACTUS, 64)),
    Carrots64(ItemInInventoryListener.factory(Material.CARROTS, 64)),
    Charcoal64(ItemInInventoryListener.factory(Material.CHARCOAL, 64)),
    ClayBlocks64(ItemInInventoryListener.factory(Material.CLAY, 64)),
    Coal64(ItemInInventoryListener.factory(Material.COAL, 64)),
    Cobblestone64(ItemInInventoryListener.factory(Material.COBBLESTONE, 64)),
    CopperIngots64(ItemInInventoryListener.factory(Material.COPPER_INGOT, 64)),
    CraftingTable64(ItemInInventoryListener.factory(Material.CRAFTING_TABLE, 64)),
    CrimsonStems64(ItemInInventoryListener.factory(Material.CRIMSON_STEM, 64)),
    DarkOakLogs64(ItemInInventoryListener.factory(Material.DARK_OAK_LOG, 64)),
    Diorite64(ItemInInventoryListener.factory(Material.DIORITE, 64)),
    Dirt64(ItemInInventoryListener.factory(Material.DIRT, 64)),
    Emeralds64(ItemInInventoryListener.factory(Material.EMERALD, 64)),
    Endstone64(ItemInInventoryListener.factory(Material.END_STONE, 64)),
    Feathers64(ItemInInventoryListener.factory(Material.FEATHER, 64)),
    Flint64(ItemInInventoryListener.factory(Material.FLINT, 64)),
    Glass64(ItemInInventoryListener.factory(Material.GLASS, 64)),
    GlowstoneBlocks64(ItemInInventoryListener.factory(Material.GLOWSTONE, 64)),
    GoldIngots64(ItemInInventoryListener.factory(Material.GOLD_INGOT, 64)),
    Granite64(ItemInInventoryListener.factory(Material.GRANITE, 64)),
    Gravel64(ItemInInventoryListener.factory(Material.GRAVEL, 64)),
    Gunpowder64(ItemInInventoryListener.factory(Material.GUNPOWDER, 64)),
    IronIngots64(ItemInInventoryListener.factory(Material.IRON_INGOT, 64)),
    JungleLogs64(ItemInInventoryListener.factory(Material.JUNGLE_LOG, 64)),
    Ladders64(ItemInInventoryListener.factory(Material.LADDER, 64)),
    LapisLazuli64(ItemInInventoryListener.factory(Material.LAPIS_LAZULI, 64)),
    Leather64(ItemInInventoryListener.factory(Material.LEATHER, 64)),
    Leaves64,
    LilyPads64(ItemInInventoryListener.factory(Material.LILY_PAD, 64)),
    NetherQuartz64(ItemInInventoryListener.factory(Material.QUARTZ, 64)),
    NetherWart64(ItemInInventoryListener.factory(Material.NETHER_WART, 64)),
    Netherrack64(ItemInInventoryListener.factory(Material.NETHERRACK, 64)),
    OakLogs64(ItemInInventoryListener.factory(Material.OAK_LOG, 64)),
    Obsidian64(ItemInInventoryListener.factory(Material.OBSIDIAN, 64)),
    Potatoes64(ItemInInventoryListener.factory(Material.POTATO, 64)),
    Rails64(ItemInInventoryListener.factory(Material.RAIL, 64)),
    Redstone64(ItemInInventoryListener.factory(Material.REDSTONE, 64)),
    RottenFlesh64(ItemInInventoryListener.factory(Material.ROTTEN_FLESH, 64)),
    Sand64(ItemInInventoryListener.factory(Material.SAND, 64)),
    Sandstone64(ItemInInventoryListener.factory(Material.SANDSTONE, 64)),
    Slimeballs64(ItemInInventoryListener.factory(Material.SLIME_BALL, 64)),
    SmoothStone64(ItemInInventoryListener.factory(Material.SMOOTH_STONE, 64)),
    SpruceLogs64(ItemInInventoryListener.factory(Material.SPRUCE_LOG, 64)),
    Stone64(ItemInInventoryListener.factory(Material.STONE, 64)),
    String64(ItemInInventoryListener.factory(Material.STRING, 64)),
    SugarCane64(ItemInInventoryListener.factory(Material.SUGAR_CANE, 64)),
    SweetBerries64(ItemInInventoryListener.factory(Material.SWEET_BERRIES, 64)),
    WarpedStems64(ItemInInventoryListener.factory(Material.WARPED_STEM, 64)),
    Wheat64(ItemInInventoryListener.factory(Material.WHEAT, 64)),
    UniqueConcreteBlocks7(MultiItemInInventoryListener.factory(Constants.Bundles.ConcreteBlocks, 7)),
    Cobwebs8(ItemInInventoryListener.factory(Material.COBWEB, 8)),
    UniqueGlazedTerracotta8(MultiItemInInventoryListener.factory(Constants.Bundles.GlazedTerracottaBlocks, 8)),
    Activate3EndPortals,
    All16DyeColors(MultiItemInInventoryListener.factory(Constants.Bundles.Dyes)),
    All26UniquePaintings,
    All3Stews(MultiItemInInventoryListener.factory(Constants.Bundles.Stews)),
    AllDiamondTools(MultiItemInInventoryListener.factory(Constants.Bundles.DiamondTools)),
    AllIronTools(MultiItemInInventoryListener.factory(Constants.Bundles.IronTools)),
    AllStoneTools(MultiItemInInventoryListener.factory(Constants.Bundles.StoneTools)),
    AllTypesOfDoorsIncludingTrapdoors(MultiItemInInventoryListener.factory(Constants.Bundles.Doors)),
    AllWoodTools(MultiItemInInventoryListener.factory(Constants.Bundles.WoodTools)),
    AnyChainArmor,
    AnyConcreteBlock(MultiItemInInventoryListener.factory(Constants.Bundles.ConcreteBlocks, UniqueCount.Any)),
    AnyGlazedTerracotta(
        MultiItemInInventoryListener.factory(
            Constants.Bundles.GlazedTerracottaBlocks,
            UniqueCount.Any
        )
    ),
    AnyTippedArrow,
    BarterWithPiglin,
    BlowUpBedInNether,
    BounceOnSlimeBlock,
    BreakDiamondTool,
    BreakPieceOfDiamondArmor,
    BreakShield,
    BreakAnyArmor,
    BreakAnyTool,
    BreedAxolotl(BreedListener.factory(EntityType.AXOLOTL)),
    BreedBee(BreedListener.factory(EntityType.BEE)),
    BreedCat(BreedListener.factory(EntityType.CAT)),
    BreedChicken(BreedListener.factory(EntityType.CHICKEN)),
    BreedCow(BreedListener.factory(EntityType.COW)),
    BreedDonkey(BreedListener.factory(EntityType.DONKEY)),
    BreedFox(BreedListener.factory(EntityType.FOX)),
    BreedGoat(BreedListener.factory(EntityType.GOAT)),
    BreedHoglin(BreedListener.factory(EntityType.HOGLIN)),
    BreedHorse(BreedListener.factory(EntityType.HORSE)),
    BreedLlama(BreedListener.factory(EntityType.LLAMA)),
    BreedMule(BreedListener.factory(EntityType.MULE)),
    BreedOcelot(BreedListener.factory(EntityType.OCELOT)),
    BreedPanda(BreedListener.factory(EntityType.PANDA)),
    BreedPig(BreedListener.factory(EntityType.PIG)),
    BreedRabbit(BreedListener.factory(EntityType.RABBIT)),
    BreedSheep(BreedListener.factory(EntityType.SHEEP)),
    BreedStrider(BreedListener.factory(EntityType.STRIDER)),
    BreedTurtle,
    BreedWolf(BreedListener.factory(EntityType.WOLF)),
    BrewPotionOfFireResistance(BrewListener.factory(PotionType.FIRE_RESISTANCE)),
    BrewPotionOfHarming(BrewListener.factory(PotionType.INSTANT_DAMAGE)),
    BrewPotionOfHealing(BrewListener.factory(PotionType.INSTANT_HEAL)),
    BrewPotionOfInvisibility(BrewListener.factory(PotionType.INVISIBILITY)),
    BrewPotionOfLeaping(BrewListener.factory(PotionType.JUMP)),
    BrewPotionOfNightVision(BrewListener.factory(PotionType.NIGHT_VISION)),
    BrewPotionOfRegeneration(BrewListener.factory(PotionType.REGEN)),
    BrewPotionOfSlowness(BrewListener.factory(PotionType.SLOWNESS)),
    BrewPotionOfStrength(BrewListener.factory(PotionType.STRENGTH)),
    BrewPotionOfSwiftness(BrewListener.factory(PotionType.SPEED)),
    BrewPotionOfWaterBreathing(BrewListener.factory(PotionType.WATER_BREATHING)),
    BrewPotionOfWeakness(BrewListener.factory(PotionType.WEAKNESS)),
    BrewAnyLingeringPotion,
    CarvePumpkin,
    CleanBannerWithCauldron(::CleanBannerListener),
    CompleteMap,
    Cook4FoodOnCampfire,
    CraftActivatorRail(CraftListener.factory(Material.ACTIVATOR_RAIL)),
    CraftAnvil(CraftListener.factory(Material.ANVIL)),
    CraftArmorStand(CraftListener.factory(Material.ARMOR_STAND)),
    CraftBeehive(CraftListener.factory(Material.BEEHIVE)),
    CraftBlastFurnace(CraftListener.factory(Material.BLAST_FURNACE)),
    CraftBookshelf(CraftListener.factory(Material.BOOKSHELF)),
    CraftCake(CraftListener.factory(Material.CAKE)),
    CraftCampfire(CraftListener.factory(Material.CAMPFIRE)),
    CraftCandle(CraftListener.factory(Material.CANDLE)),
    CraftCartographyTable(CraftListener.factory(Material.CARTOGRAPHY_TABLE)),
    CraftClock(CraftListener.factory(Material.CLOCK)),
    CraftCompass(CraftListener.factory(Material.COMPASS)),
    CraftDaylightDetector(CraftListener.factory(Material.DAYLIGHT_DETECTOR)),
    CraftDispenser(CraftListener.factory(Material.DISPENSER)),
    CraftDropper(CraftListener.factory(Material.DROPPER)),
    CraftEndCrystal(CraftListener.factory(Material.END_CRYSTAL)),
    CraftEnderChest(CraftListener.factory(Material.ENDER_CHEST)),
    CraftFireCharge(CraftListener.factory(Material.FIRE_CHARGE)),
    CraftFletchingTable(CraftListener.factory(Material.FLETCHING_TABLE)),
    CraftGrindstone(CraftListener.factory(Material.GRINDSTONE)),
    CraftHoneyBlock(CraftListener.factory(Material.HONEY_BLOCK)),
    CraftHopper(CraftListener.factory(Material.HOPPER)),
    CraftJackOlantern(CraftListener.factory(Material.JACK_O_LANTERN)),
    CraftJukebox(CraftListener.factory(Material.JUKEBOX)),
    CraftLectern(CraftListener.factory(Material.LECTERN)),
    CraftLoom(CraftListener.factory(Material.LOOM)),
    CraftMagmaCream(CraftListener.factory(Material.MAGMA_CREAM)),
    CraftNoteBlock(CraftListener.factory(Material.NOTE_BLOCK)),
    CraftObserver(CraftListener.factory(Material.OBSERVER)),
    CraftPainting(CraftListener.factory(Material.PAINTING)),
    CraftPiston(CraftListener.factory(Material.PISTON)),
    CraftPoweredRail(CraftListener.factory(Material.POWERED_RAIL)),
    CraftPrismarineBrick(CraftListener.factory(Material.PRISMARINE_BRICKS)),
    CraftRabbitStew(CraftListener.factory(Material.RABBIT_STEW)),
    CraftRedNetherBrick(CraftListener.factory(Material.RED_NETHER_BRICKS)),
    CraftRedstoneComparator(CraftListener.factory(Material.COMPARATOR)),
    CraftRedstoneLamp(CraftListener.factory(Material.REDSTONE_LAMP)),
    CraftRedstoneRepeater(CraftListener.factory(Material.REPEATER)),
    CraftRespawnAnchor(CraftListener.factory(Material.RESPAWN_ANCHOR)),
    CraftScaffolding(CraftListener.factory(Material.SCAFFOLDING)),
    CraftSmoker(CraftListener.factory(Material.SMOKER)),
    CraftSoulCampfire(CraftListener.factory(Material.SOUL_CAMPFIRE)),
    CraftSoulLantern(CraftListener.factory(Material.SOUL_LANTERN)),
    CraftSpyglass(CraftListener.factory(Material.SPYGLASS)),
    CraftStickyPiston(CraftListener.factory(Material.STICKY_PISTON)),
    CraftStonecutter(CraftListener.factory(Material.STONECUTTER)),
    CraftTarget(CraftListener.factory(Material.TARGET)),
    CraftTrappedChest(CraftListener.factory(Material.TRAPPED_CHEST)),
    CreateDirtPathBlock,
    DestroyMobSpawner,
    Die(::PlayerDeathListener),
    DrinkHoneyBottle(ConsumeListener.factory(Material.HONEY_BOTTLE)),
    DrinkMilk(ConsumeListener.factory(Material.MILK_BUCKET)),
    DrySponge,
    DyeLeatherArmorPiece,
    DyeSheep,
    EatApple(ConsumeListener.factory(Material.APPLE)),
    EatBakedPotato(ConsumeListener.factory(Material.BAKED_POTATO)),
    EatBeetroot(ConsumeListener.factory(Material.BEETROOT)),
    EatBeetrootSoup(ConsumeListener.factory(Material.BEETROOT_SOUP)),
    EatBread(ConsumeListener.factory(Material.BREAD)),
    EatCarrot(ConsumeListener.factory(Material.CARROT)),
    EatChorusFruit(ConsumeListener.factory(Material.CHORUS_FRUIT)),
    EatCookedBeef(ConsumeListener.factory(Material.COOKED_BEEF)),
    EatCookedChicken(ConsumeListener.factory(Material.COOKED_CHICKEN)),
    EatCookedCod(ConsumeListener.factory(Material.COOKED_COD)),
    EatCookedMutton(ConsumeListener.factory(Material.COOKED_MUTTON)),
    EatCookedPorkchop(ConsumeListener.factory(Material.COOKED_PORKCHOP)),
    EatCookedRabbit(ConsumeListener.factory(Material.COOKED_RABBIT)),
    EatCookedSalmon(ConsumeListener.factory(Material.COOKED_SALMON)),
    EatCookie(ConsumeListener.factory(Material.COOKIE)),
    EatDriedKelp(ConsumeListener.factory(Material.DRIED_KELP)),
    EatEnchantedGoldenApple(ConsumeListener.factory(Material.ENCHANTED_GOLDEN_APPLE)),
    EatGlowBerry(ConsumeListener.factory(Material.GLOW_BERRIES)),
    EatGoldenApple(ConsumeListener.factory(Material.GOLDEN_APPLE)),
    EatGoldenCarrot(ConsumeListener.factory(Material.GOLDEN_CARROT)),
    EatMelonSlice(ConsumeListener.factory(Material.MELON_SLICE)),
    EatMushroomStew(ConsumeListener.factory(Material.MUSHROOM_STEW)),
    EatPoisonPotato(ConsumeListener.factory(Material.POISONOUS_POTATO)),
    EatPotato(ConsumeListener.factory(Material.POTATO)),
    EatPufferfish(ConsumeListener.factory(Material.PUFFERFISH)),
    EatPumpkinPie(ConsumeListener.factory(Material.PUMPKIN_PIE)),
    EatRabbitStew(ConsumeListener.factory(Material.RABBIT_STEW)),
    EatRawBeef(ConsumeListener.factory(Material.BEEF)),
    EatRawChicken(ConsumeListener.factory(Material.CHICKEN)),
    EatRawCod(ConsumeListener.factory(Material.COD)),
    EatRawMutton(ConsumeListener.factory(Material.MUTTON)),
    EatRawPorkchop(ConsumeListener.factory(Material.PORKCHOP)),
    EatRawRabbit(ConsumeListener.factory(Material.RABBIT)),
    EatRawSalmon(ConsumeListener.factory(Material.SALMON)),
    EatRottenFlesh(ConsumeListener.factory(Material.ROTTEN_FLESH)),
    EatSpiderEye(ConsumeListener.factory(Material.SPIDER_EYE)),
    EatSuspiciousStew(ConsumeListener.factory(Material.SUSPICIOUS_STEW)),
    EatSweetBerry(ConsumeListener.factory(Material.SWEET_BERRIES)),
    EatTropicalFish(ConsumeListener.factory(Material.TROPICAL_FISH)),
    EnchantBook(EnchantListener.factory(Material.BOOK)),
    EnchantFishingPole(EnchantListener.factory(Material.FISHING_ROD)),
    EnchantWoodenTool,
    EnterBadlandsBiome,
    EnterBambooJungleBiome,
    EnterDesertTemple(EnterStructureListener.factory(StructureType.DESERT_PYRAMID)),
    EnterDesertVillage(EnterStructureListener.factory(VillageType.DesertVillage)),
    EnterDungeon,
    EnterEndCity(EnterStructureListener.factory(StructureType.END_CITY)),
    EnterIceSpikesBiome,
    EnterIgloo(EnterStructureListener.factory(StructureType.IGLOO)),
    EnterJungleBiome,
    EnterJungleTemple(EnterStructureListener.factory(StructureType.JUNGLE_PYRAMID)),
    EnterLargeTreeTaigaBiome,
    EnterMushroomIslandBiome,
    EnterPlainsVillage(EnterStructureListener.factory(VillageType.PlainsVillage)),
    EnterRavine,
    EnterSavannaVillage(EnterStructureListener.factory(VillageType.SavannaVillage)),
    EnterShatteredSavannaBiome,
    EnterShipwreck(EnterStructureListener.factory(StructureType.SHIPWRECK)),
    EnterTaigaVillage(EnterStructureListener.factory(VillageType.TaigaVillage)),
    EnterTundraBiome,
    EnterTundraVillage(EnterStructureListener.factory(VillageType.SnowyVillage)),
    EnterWarmOceanBiome,
    EnterWitchHut(EnterStructureListener.factory(StructureType.SWAMP_HUT)),
    EnterAmethystGeode,
    EquipCurseOfBindingItem,
    FeedWheatToHorse,
    FillComposter,
    FullDiamondArmor,
    FullGoldArmor,
    FullIronArmor,
    FullLeatherArmor,
    FullNetheriteArmor,
    GetSkeletonToShootSkeleton,
    GetAbsorptionEffect(PotionEffectListener.factory(PotionEffectType.ABSORPTION)),
    GetBlindnessEffect(PotionEffectListener.factory(PotionEffectType.BLINDNESS)),
    GetDolphinsGraceEffect(PotionEffectListener.factory(PotionEffectType.DOLPHINS_GRACE)),
    GetGlowingEffect(PotionEffectListener.factory(PotionEffectType.GLOWING)),
    GetHungerEffect(PotionEffectListener.factory(PotionEffectType.HUNGER)),
    GetLevitationEffect(PotionEffectListener.factory(PotionEffectType.LEVITATION)),
    GetMiningFatigueEffect(PotionEffectListener.factory(PotionEffectType.SLOW_DIGGING)),
    GetRegenerationEffect(PotionEffectListener.factory(PotionEffectType.REGENERATION)),
    GetResistanceEffect(PotionEffectListener.factory(PotionEffectType.DAMAGE_RESISTANCE)),
    GetWitherEffect(PotionEffectListener.factory(PotionEffectType.WITHER)),
    GrowDarkOakTree(StructureGrowListener.factory(TreeType.DARK_OAK)),
    GrowGiantMushroom,
    GrowLargeJungleTree(StructureGrowListener.factory(TreeType.JUNGLE)),
    GrowLargeSpruceTree(StructureGrowListener.factory(TreeType.MEGA_REDWOOD)),
    HaveDolphinLeadYouToTreasure,
    HitYourselfWithArrow,
    KillAxolotl(KillListener.factory(EntityType.AXOLOTL)),
    KillBabyVillager,
    KillBabyZombieWithArrow,
    KillBat(KillListener.factory(EntityType.BAT)),
    KillBee(KillListener.factory(EntityType.BEE)),
    KillBlaze(KillListener.factory(EntityType.BLAZE)),
    KillBlazeWithSnowballs,
    KillCat(KillListener.factory(EntityType.CAT)),
    KillCaveSpider(KillListener.factory(EntityType.CAVE_SPIDER)),
    KillChicken(KillListener.factory(EntityType.CHICKEN)),
    KillCod(KillListener.factory(EntityType.COD)),
    KillCow(KillListener.factory(EntityType.COW)),
    KillCreeper(KillListener.factory(EntityType.CREEPER)),
    KillCreeperWithAnotherCreeper,
    KillCreeperWithTnt,
    KillDolphin(KillListener.factory(EntityType.DOLPHIN)),
    KillDonkey(KillListener.factory(EntityType.DONKEY)),
    KillDrowned(KillListener.factory(EntityType.DROWNED)),
    KillDrownedHoldingTrident,
    KillElderGuardian(KillListener.factory(EntityType.ELDER_GUARDIAN)),
    KillEnderDragon(KillListener.factory(EntityType.ENDER_DRAGON)),
    KillEnderDragonWithoutBeds,
    KillEnderman(KillListener.factory(EntityType.ENDERMAN)),
    KillEndermite(KillListener.factory(EntityType.ENDERMITE)),
    KillEvoker(KillListener.factory(EntityType.EVOKER)),
    KillFox(KillListener.factory(EntityType.FOX)),
    KillGhast(KillListener.factory(EntityType.GHAST)),
    KillGlowSquid(KillListener.factory(EntityType.GLOW_SQUID)),
    KillGuardian(KillListener.factory(EntityType.GUARDIAN)),
    KillHoglin(KillListener.factory(EntityType.HOGLIN)),
    KillHorse(KillListener.factory(EntityType.HORSE)),
    KillHusk(KillListener.factory(EntityType.HUSK)),
    KillIronGolem(KillListener.factory(EntityType.IRON_GOLEM)),
    KillLlama(KillListener.factory(EntityType.LLAMA)),
    KillMagmaCube(KillListener.factory(EntityType.MAGMA_CUBE)),
    KillMobWhileItsOnFire,
    KillMobWithTamedWolf,
    KillMobWithDripstone,
    KillMobWithFallDamage,
    KillMooshroom(KillListener.factory(EntityType.MUSHROOM_COW)),
    KillMule(KillListener.factory(EntityType.MULE)),
    KillOcelot(KillListener.factory(EntityType.OCELOT)),
    KillPanda(KillListener.factory(EntityType.PANDA)),
    KillParrot(KillListener.factory(EntityType.PARROT)),
    KillPhantom(KillListener.factory(EntityType.PHANTOM)),
    KillPig(KillListener.factory(EntityType.PIG)),
    KillPiglin(KillListener.factory(EntityType.PIGLIN)),
    KillPiglinBrute(KillListener.factory(EntityType.PIGLIN_BRUTE)),
    KillPillager(KillListener.factory(EntityType.PILLAGER)),
    KillPolarBear(KillListener.factory(EntityType.POLAR_BEAR)),
    KillPufferfish(KillListener.factory(EntityType.PUFFERFISH)),
    KillRabbit(KillListener.factory(EntityType.RABBIT)),
    KillRavager(KillListener.factory(EntityType.RAVAGER)),
    KillSalmon(KillListener.factory(EntityType.SALMON)),
    KillSheep(KillListener.factory(EntityType.SHEEP)),
    KillShulker(KillListener.factory(EntityType.SHULKER)),
    KillSilverfish(KillListener.factory(EntityType.SILVERFISH)),
    KillSkeleton(KillListener.factory(EntityType.SKELETON)),
    KillSkeletonWithoutItDamagingYou,
    KillSlime(KillListener.factory(EntityType.SLIME)),
    KillSnowGolem(KillListener.factory(EntityType.SNOWMAN)),
    KillSpider(KillListener.factory(EntityType.SPIDER)),
    KillSpiderJockey,
    KillSquid(KillListener.factory(EntityType.SQUID)),
    KillStray(KillListener.factory(EntityType.STRAY)),
    KillStrider(KillListener.factory(EntityType.STRIDER)),
    KillTropicalFish(KillListener.factory(EntityType.TROPICAL_FISH)),
    KillTurtle(KillListener.factory(EntityType.TURTLE)),
    KillVex(KillListener.factory(EntityType.VEX)),
    KillVillager(KillListener.factory(EntityType.VILLAGER)),
    KillVindicator(KillListener.factory(EntityType.VINDICATOR)),
    KillWitch(KillListener.factory(EntityType.WITCH)),
    KillWither(KillListener.factory(EntityType.WITHER)),
    KillWitherSkeleton(KillListener.factory(EntityType.WITHER_SKELETON)),
    KillWolf(KillListener.factory(EntityType.WOLF)),
    KillZoglin(KillListener.factory(EntityType.ZOGLIN)),
    KillZombie(KillListener.factory(EntityType.ZOMBIE)),
    KillZombiePiglin(KillListener.factory(EntityType.ZOMBIFIED_PIGLIN)),
    KillZombieVillager(KillListener.factory(EntityType.ZOMBIE_VILLAGER)),
    LightCreeperWithFlintSteel,
    LightTntWithFlintSteel,
    LightTntWithRedstone,
    LootBuriedTreasure(LootableListener.factory(LootTables.BURIED_TREASURE)),
    LootRuinedPortalChest(LootableListener.factory(LootTables.RUINED_PORTAL)),
    MakeEfficiency5Tool(PlayerUpdateEnchantmentListener.factory(Enchantment.DIG_SPEED, 5)),
    MakePower5Bow(PlayerUpdateEnchantmentListener.factory(Enchantment.ARROW_DAMAGE, 5)),
    MakeSharpness5Sword(PlayerUpdateEnchantmentListener.factory(Enchantment.DAMAGE_ALL, 5)),
    MakeWitchPoisonItself,
    MineAncientDebris(BlockBreakListener.factory(Material.ANCIENT_DEBRIS)),
    MineCoalOre(BlockBreakListener.factory(Material.COAL_ORE)),
    MineCopperOre(BlockBreakListener.factory(Material.COPPER_ORE)),
    MineDiamondOre(BlockBreakListener.factory(Material.DIAMOND_ORE)),
    MineEmeraldOre(BlockBreakListener.factory(Material.EMERALD_ORE)),
    MineGoldOre(BlockBreakListener.factory(Material.GOLD_ORE)),
    MineIronOre(BlockBreakListener.factory(Material.IRON_ORE)),
    MineLapisLazuliOre(BlockBreakListener.factory(Material.LAPIS_ORE)),
    MineNetherGoldOre(BlockBreakListener.factory(Material.NETHER_GOLD_ORE)),
    MineNetherQuartzOre(BlockBreakListener.factory(Material.NETHER_QUARTZ_ORE)),
    MineRedstoneOre(BlockBreakListener.factory(Material.REDSTONE_ORE)),
    Obtain12UniqueFlowers(MultiItemInInventoryListener.factory(Constants.Bundles.Flowers, 12)),
    ObtainAmethystShard(ItemInInventoryListener.factory(Material.AMETHYST_SHARD)),
    ObtainMendingBook,
    ObtainNameTag(ItemInInventoryListener.factory(Material.NAME_TAG)),
    ObtainNautilusShell(ItemInInventoryListener.factory(Material.NAUTILUS_SHELL)),
    ObtainSaddle(ItemInInventoryListener.factory(Material.SADDLE)),
    ObtainTrident(ItemInInventoryListener.factory(Material.TRIDENT)),
    ObtainAnyMobHead(MultiItemInInventoryListener.factory(Constants.Bundles.MobHeads, UniqueCount.Any)),
    ObtainDiamondHorseArmor(ItemInInventoryListener.factory(Material.DIAMOND_HORSE_ARMOR)),
    ObtainGoldHorseArmor(ItemInInventoryListener.factory(Material.GOLDEN_HORSE_ARMOR)),
    ObtainIronHorseArmor(ItemInInventoryListener.factory(Material.IRON_HORSE_ARMOR)),
    ObtainLeatherHorseArmor(ItemInInventoryListener.factory(Material.LEATHER_HORSE_ARMOR)),
    PlantBamboo(BlockPlaceListener.factory(Material.BAMBOO_SAPLING)),
    PlantBeetrootSeed(BlockPlaceListener.factory(Material.BEETROOTS)),
    PlantChorusFruit(BlockPlaceListener.factory(Material.CHORUS_PLANT)),
    PlantCocoaBean(BlockPlaceListener.factory(Material.COCOA)),
    PlantNetherWart(BlockPlaceListener.factory(Material.NETHER_WART)),
    PlantPumpkinSeed(BlockPlaceListener.factory(Material.PUMPKIN_STEM)),
    PlantSugarCane(BlockPlaceListener.factory(Material.SUGAR_CANE)),
    PlantWheatSeed(BlockPlaceListener.factory(Material.WHEAT_SEEDS)),
    PlantAnySapling,
    PlantSomethingInFlowerPot,
    PlayMusicDisc,
    PushMobWithPiston,
    ReachLevel10(LevelChangeListener.factory(10)),
    ReachLevel25(LevelChangeListener.factory(25)),
    ReachBuildLimitY256,
    ReachY0InEnd,
    RepairToolInAnvil,
    RideBoatWithCreeper,
    RideMinecartOnRail,
    RidePig,
    RingBell,
    SetYourSpawnWithBed,
    ShearMooshroom,
    ShearSheep,
    ShootBatWithArrow,
    ShootBell,
    ShootFireworkFromCrossbow,
    StandOnBedrock,
    StareAtSunWithSpyglass,
    StripLog,
    SwimInDesertWell,
    SwimInLavaWithFireResistance,
    TameCat(TameListener.factory(EntityType.CAT)),
    TameDonkey(TameListener.factory(EntityType.DONKEY)),
    TameHorse(TameListener.factory(EntityType.HORSE)),
    TameLlama(TameListener.factory(EntityType.LLAMA)),
    TameMule(TameListener.factory(EntityType.MULE)),
    TameParrot(TameListener.factory(EntityType.PARROT)),
    TameWolf(TameListener.factory(EntityType.WOLF)),
    ThrowDiamondInLava,
    ThrowEnderPearl(ProjectileLaunchListener.factory(EntityType.ENDER_PEARL)),
    ThrowSnowball(ProjectileLaunchListener.factory(EntityType.SNOWBALL)),
    ThrowEgg,
    TrapMobInBoat,
    UseAnyDyeOnSign,
    UseBonemealOnGrass,
    WearCarvedPumpkin,
    WriteBook,
    Unknown;

    fun addListener(state: State, player: Player): Listener {
        val listener = listenerFactory(state, this, player)
        Bukkit.getServer().pluginManager.registerEvents(listener, state.plugin)
        return listener
    }
}
