package util

import game.State
import listener.AdvancementListener
import listener.ItemInInventoryListener
import listener.NoOpListener
import listener.ObjectiveListener
import org.bukkit.Bukkit
import org.bukkit.Material
import org.bukkit.advancement.Advancement
import org.bukkit.entity.Player

enum class Objective(val listenerFactory: (State, Objective, Player) -> ObjectiveListener) {
    ACompleteCatalogueAdvancement(AdvancementListener.factory("husbandry/complete_catalogue")),
    AFuriousCocktailAdvancement(AdvancementListener.factory("nether/all_potions")),
    ASeedyPlaceAdvancement(AdvancementListener.factory("husbandry/plant_seed")),
    ATerribleFortressAdvancement(AdvancementListener.factory("nether/find_fortress")),
    AcquireHardwareAdvancement(AdvancementListener.factory("story/smelt_iron")),
    ArbalisticAdvancement(AdvancementListener.factory("adventure/arbalistic")),
    BeeOurGuestAdvancement(AdvancementListener.factory("husbandry/safely_harvest_honey")),
    BestFriendsForeverAdvancement(AdvancementListener.factory("husbandry/tame_an_animal")),
    BullseyeAdvancement(AdvancementListener.factory("adventure/bullseye")),
    CountryLodeTakeMeHomeAdvancement(AdvancementListener.factory("nether/use_lodestone")),
    CoverMeWithDiamondsAdvancement(AdvancementListener.factory("story/shiny_gear")),
    DiamondsAdvancement(AdvancementListener.factory("story/mine_diamond")),
    EnchanterAdvancement(AdvancementListener.factory("story/enchant_item")),
    FishyBusinessAdvancement(AdvancementListener.factory("husbandry/fishy_business")),
    GettingAnUpgradeAdvancement(AdvancementListener.factory("story/upgrade_tools")),
    GlowAndBeholdAdvancement(AdvancementListener.factory("husbandry/make_a_sign_glow")),
    GreatViewFromUpHereAdvancement(AdvancementListener.factory("end/levitate")),
    HeroOfTheVillageAdvancement(AdvancementListener.factory("adventure/hero_of_the_village")),
    HiddenInTheDepthsAdvancement(AdvancementListener.factory("nether/obtain_ancient_debris")),
    HiredHelpAdvancement(AdvancementListener.factory("adventure/summon_iron_golem")),
    HotStuffAdvancement(AdvancementListener.factory("story/lava_bucket")),
    HotTouristDestinationsAdvancement(AdvancementListener.factory("nether/explore_nether")),
    IceBucketChallengeAdvancement(AdvancementListener.factory("story/form_obsidian")),
    IntoFireAdvancement(AdvancementListener.factory("nether/obtain_blaze_rod")),
    IsItABalloonAdvancement(AdvancementListener.factory("adventure/spyglass_at_ghast")),
    IsItAPlaneAdvancement(AdvancementListener.factory("adventure/spyglass_at_dragon")),
    IsntItIronPickAdvancement(AdvancementListener.factory("story/iron_tools")),
    IsItABirdAdvancement(AdvancementListener.factory("adventure/spyglass_at_parrot")),
    LocalBreweryAdvancement(AdvancementListener.factory("nether/brew_potion")),
    MonsterHunterAdvancement(AdvancementListener.factory("adventure/kill_a_mob")),
    NotQuiteNineLivesAdvancement(AdvancementListener.factory("nether/charge_respawn_anchor")),
    NotTodayThankYouAdvancement(AdvancementListener.factory("story/deflect_arrow")),
    OhShinyAdvancement(AdvancementListener.factory("nether/distract_piglin")),
    OlBetsyAdvancement(AdvancementListener.factory("adventure/ol_betsy")),
    PostmortalAdvancement(AdvancementListener.factory("adventure/totem_of_undying")),
    RemoteGetawayAdvancement(AdvancementListener.factory("end/enter_end_gateway")),
    ReturnToSenderAdvancement(AdvancementListener.factory("nether/return_to_sender")),
    SeriousDedicationAdvancement(AdvancementListener.factory("husbandry/obtain_netherite_hoe")),
    SkysTheLimitAdvancement(AdvancementListener.factory("end/elytra")),
    SniperDuelAdvancement(AdvancementListener.factory("adventure/sniper_duel")),
    SpookyScarySkeletonAdvancement(AdvancementListener.factory("nether/get_wither_skull")),
    StickySituationAdvancement(AdvancementListener.factory("adventure/honey_block_slide")),
    StoneAgeAdvancement(AdvancementListener.factory("story/mine_stone")),
    SubspaceBubbleAdvancement(AdvancementListener.factory("nether/fast_travel")),
    SuitUpAdvancement(AdvancementListener.factory("story/obtain_armor")),
    SweetDreamsAdvancement(AdvancementListener.factory("adventure/sleep_in_bed")),
    TacticalFishingAdvancement(AdvancementListener.factory("husbandry/tactical_fishing")),
    TakeAimAdvancement(AdvancementListener.factory("adventure/shoot_arrow")),
    TheCutestPredatorAdvancement(AdvancementListener.factory("husbandry/axolotl_in_a_bucket")),
    TheEndAdvancement(AdvancementListener.factory("end/root")),
    TheEndAgainAdvancement(AdvancementListener.factory("end/respawn_dragon")),
    TheHealingPowerOfFriendshipAdvancement(AdvancementListener.factory("husbandry/kill_axolotl_target")),
    TheNextGenerationAdvancement(AdvancementListener.factory("end/dragon_egg")),
    TheParrotsAndTheBatsAdvancement(AdvancementListener.factory("husbandry/breed_an_animal")),
    ThisBoatHasLegsAdvancement(AdvancementListener.factory("nether/ride_strider")),
    ThoseWereTheDaysAdvancement(AdvancementListener.factory("nether/find_bastion")),
    TotalBeelocationAdvancement(AdvancementListener.factory("husbandry/silk_touch_nest")),
    TwoBirdsOneArrowAdvancement(AdvancementListener.factory("adventure/two_birds_one_arrow")),
    UneasyAllianceAdvancement(AdvancementListener.factory("nether/uneasy_alliance")),
    VoluntaryExileAdvancement(AdvancementListener.factory("adventure/voluntary_exile")),
    WarPigsAdvancement(AdvancementListener.factory("nether/loot_bastion")),
    WaxOffAdvancement(AdvancementListener.factory("husbandry/wax_off")),
    WaxOnAdvancement(AdvancementListener.factory("husbandry/wax_on")),
    WeNeedToGoDeeperAdvancement(AdvancementListener.factory("story/enter_the_nether")),
    WhatADealAdvancement(AdvancementListener.factory("adventure/trade")),
    WhateverFloatsYourGoatAdvancement(AdvancementListener.factory("husbandry/ride_a_boat_with_a_goat")),
    WhoIsCuttingOnionsAdvancement(AdvancementListener.factory("nether/obtain_crying_obsidian")),
    WhosThePillagerNowAdvancement(AdvancementListener.factory("adventure/whos_the_pillager_now")),
    WitheringHeightsAdvancement(AdvancementListener.factory("nether/summon_wither")),
    YouNeedAMintAdvancement(AdvancementListener.factory("end/dragon_breath")),
    ZombieDoctorAdvancement(AdvancementListener.factory("story/cure_zombie_villager")),
    UniqueConcreteBlocks12(::NoOpListener),
    BlackStainedGlass16(ItemInInventoryListener.factory(Material.BLACK_STAINED_GLASS, 16)),
    BlackWool16(ItemInInventoryListener.factory(Material.BLACK_WOOL, 16)),
    BlueIce16(ItemInInventoryListener.factory(Material.BLUE_ICE, 16)),
    BlueStainedGlass16(ItemInInventoryListener.factory(Material.BLUE_STAINED_GLASS, 16)),
    BlueWool16(ItemInInventoryListener.factory(Material.BLUE_WOOL, 16)),
    BrownStainedGlass16(ItemInInventoryListener.factory(Material.BROWN_STAINED_GLASS, 16)),
    BrownWool16(ItemInInventoryListener.factory(Material.BROWN_WOOL, 16)),
    CyanStainedGlass16(ItemInInventoryListener.factory(Material.CYAN_STAINED_GLASS, 16)),
    CyanWool16(ItemInInventoryListener.factory(Material.CYAN_WOOL, 16)),
    Eggs16(ItemInInventoryListener.factory(Material.EGG, 16)),
    EnderPearls16(ItemInInventoryListener.factory(Material.ENDER_PEARL, 16)),
    GrassBlocks16(ItemInInventoryListener.factory(Material.GRASS_BLOCK, 16)),
    GrayStainedGlass16(ItemInInventoryListener.factory(Material.GRAY_STAINED_GLASS, 16)),
    GrayWool16(ItemInInventoryListener.factory(Material.GRAY_WOOL, 16)),
    GreenStainedGlass16(ItemInInventoryListener.factory(Material.GREEN_STAINED_GLASS, 16)),
    GreenWool16(ItemInInventoryListener.factory(Material.GREEN_WOOL, 16)),
    InkSacks16(ItemInInventoryListener.factory(Material.INK_SAC, 16)),
    LightBlueStainedGlass16(ItemInInventoryListener.factory(Material.LIGHT_BLUE_STAINED_GLASS, 16)),
    LightBlueWool16(ItemInInventoryListener.factory(Material.LIGHT_BLUE_WOOL, 16)),
    LightGrayStainedGlass16(ItemInInventoryListener.factory(Material.LIGHT_GRAY_STAINED_GLASS, 16)),
    LightGrayWool16(ItemInInventoryListener.factory(Material.LIGHT_GRAY_WOOL, 16)),
    LimeGreenStainedGlass16(ItemInInventoryListener.factory(Material.LIME_STAINED_GLASS, 16)),
    LimeGreenWool16(ItemInInventoryListener.factory(Material.LIME_WOOL, 16)),
    MagentaStainedGlass16(ItemInInventoryListener.factory(Material.MAGENTA_STAINED_GLASS, 16)),
    MagentaWool16(ItemInInventoryListener.factory(Material.MAGENTA_WOOL, 16)),
    OrangeStainedGlass16(ItemInInventoryListener.factory(Material.ORANGE_STAINED_GLASS, 16)),
    OrangeWool16(ItemInInventoryListener.factory(Material.ORANGE_WOOL, 16)),
    PinkStainedGlass16(ItemInInventoryListener.factory(Material.PINK_STAINED_GLASS, 16)),
    PinkWool16(ItemInInventoryListener.factory(Material.PINK_WOOL, 16)),
    Podzol16(ItemInInventoryListener.factory(Material.PODZOL, 16)),
    Pumpkins16(ItemInInventoryListener.factory(Material.PUMPKIN, 16)),
    PurpleStainedGlass16(ItemInInventoryListener.factory(Material.PURPLE_STAINED_GLASS, 16)),
    PurpleWool16(ItemInInventoryListener.factory(Material.PURPLE_WOOL, 16)),
    RedStainedGlass16(ItemInInventoryListener.factory(Material.RED_STAINED_GLASS, 16)),
    RedWool16(ItemInInventoryListener.factory(Material.RED_WOOL, 16)),
    TintedGlass16(ItemInInventoryListener.factory(Material.TINTED_GLASS, 16)),
    WhiteStainedGlass16(ItemInInventoryListener.factory(Material.WHITE_STAINED_GLASS, 16)),
    WhiteWool16(ItemInInventoryListener.factory(Material.WHITE_WOOL, 16)),
    YellowStainedGlass16(ItemInInventoryListener.factory(Material.YELLOW_STAINED_GLASS, 16)),
    YellowWool16(ItemInInventoryListener.factory(Material.YELLOW_WOOL, 16)),
    UniqueConcreteBlocks3(::NoOpListener),
    BlazeRods32(ItemInInventoryListener.factory(Material.BLAZE_ROD, 32)),
    Diamonds32(ItemInInventoryListener.factory(Material.DIAMOND, 32)),
    SpiderEyes32(ItemInInventoryListener.factory(Material.SPIDER_EYE, 32)),
    AcaciaLogs64(ItemInInventoryListener.factory(Material.ACACIA_LOG, 64)),
    AmethystShards64(ItemInInventoryListener.factory(Material.AMETHYST_SHARD, 64)),
    Andesite64(ItemInInventoryListener.factory(Material.ANDESITE, 64)),
    Apples64(ItemInInventoryListener.factory(Material.APPLE, 64)),
    Arrows64(ItemInInventoryListener.factory(Material.ARROW, 64)),
    BirchLogs64(ItemInInventoryListener.factory(Material.BIRCH_LOG, 64)),
    Bones64(ItemInInventoryListener.factory(Material.BONE, 64)),
    Cacti64(ItemInInventoryListener.factory(Material.CACTUS, 64)),
    Carrots64(ItemInInventoryListener.factory(Material.CARROTS, 64)),
    Charcoal64(ItemInInventoryListener.factory(Material.CHARCOAL, 64)),
    ClayBlocks64(ItemInInventoryListener.factory(Material.CLAY, 64)),
    Coal64(ItemInInventoryListener.factory(Material.COAL, 64)),
    Cobblestone64(ItemInInventoryListener.factory(Material.COBBLESTONE, 64)),
    CopperIngots64(ItemInInventoryListener.factory(Material.COPPER_INGOT, 64)),
    CraftingTable64(ItemInInventoryListener.factory(Material.CRAFTING_TABLE, 64)),
    CrimsonStems64(ItemInInventoryListener.factory(Material.CRIMSON_STEM, 64)),
    DarkOakLogs64(ItemInInventoryListener.factory(Material.DARK_OAK_LOG, 64)),
    Diorite64(ItemInInventoryListener.factory(Material.DIORITE, 64)),
    Dirt64(ItemInInventoryListener.factory(Material.DIRT, 64)),
    Emeralds64(ItemInInventoryListener.factory(Material.EMERALD, 64)),
    Endstone64(ItemInInventoryListener.factory(Material.END_STONE, 64)),
    Feathers64(ItemInInventoryListener.factory(Material.FEATHER, 64)),
    Flint64(ItemInInventoryListener.factory(Material.FLINT, 64)),
    Glass64(ItemInInventoryListener.factory(Material.GLASS, 64)),
    GlowstoneBlocks64(ItemInInventoryListener.factory(Material.GLOWSTONE, 64)),
    GoldIngots64(ItemInInventoryListener.factory(Material.GOLD_INGOT, 64)),
    Granite64(ItemInInventoryListener.factory(Material.GRANITE, 64)),
    Gravel64(ItemInInventoryListener.factory(Material.GRAVEL, 64)),
    Gunpowder64(ItemInInventoryListener.factory(Material.GUNPOWDER, 64)),
    IronIngots64(ItemInInventoryListener.factory(Material.IRON_INGOT, 64)),
    JungleLogs64(ItemInInventoryListener.factory(Material.JUNGLE_LOG, 64)),
    Ladders64(ItemInInventoryListener.factory(Material.LADDER, 64)),
    LapisLazuli64(ItemInInventoryListener.factory(Material.LAPIS_LAZULI, 64)),
    Leather64(ItemInInventoryListener.factory(Material.LEATHER, 64)),
    Leaves64(::NoOpListener),
    LilyPads64(ItemInInventoryListener.factory(Material.LILY_PAD, 64)),
    NetherQuartz64(ItemInInventoryListener.factory(Material.QUARTZ, 64)),
    NetherWart64(ItemInInventoryListener.factory(Material.NETHER_WART, 64)),
    Netherrack64(ItemInInventoryListener.factory(Material.NETHERRACK, 64)),
    OakLogs64(ItemInInventoryListener.factory(Material.OAK_LOG, 64)),
    Obsidian64(ItemInInventoryListener.factory(Material.OBSIDIAN, 64)),
    Potatoes64(ItemInInventoryListener.factory(Material.POTATO, 64)),
    Rails64(ItemInInventoryListener.factory(Material.RAIL, 64)),
    Redstone64(ItemInInventoryListener.factory(Material.REDSTONE, 64)),
    RottenFlesh64(ItemInInventoryListener.factory(Material.ROTTEN_FLESH, 64)),
    Sand64(ItemInInventoryListener.factory(Material.SAND, 64)),
    Sandstone64(ItemInInventoryListener.factory(Material.SANDSTONE, 64)),
    Slimeballs64(ItemInInventoryListener.factory(Material.SLIME_BALL, 64)),
    SmoothStone64(ItemInInventoryListener.factory(Material.SMOOTH_STONE, 64)),
    SpruceLogs64(ItemInInventoryListener.factory(Material.SPRUCE_LOG, 64)),
    Stone64(ItemInInventoryListener.factory(Material.STONE, 64)),
    String64(ItemInInventoryListener.factory(Material.STRING, 64)),
    SugarCane64(ItemInInventoryListener.factory(Material.SUGAR_CANE, 64)),
    SweetBerries64(ItemInInventoryListener.factory(Material.SWEET_BERRIES, 64)),
    WarpedStems64(ItemInInventoryListener.factory(Material.WARPED_STEM, 64)),
    Wheat64(ItemInInventoryListener.factory(Material.WHEAT, 64)),
    UniqueConcreteBlocks7(::NoOpListener),
    Cobwebs8(ItemInInventoryListener.factory(Material.COBWEB, 8)),
    UniqueGlazedTerracotta8(::NoOpListener),
    Activate3EndPortals(::NoOpListener),
    All16DyeColors(::NoOpListener),
    All26UniquePaintings(::NoOpListener),
    All3Stews(::NoOpListener),
    AllDiamondTools(::NoOpListener),
    AllIronTools(::NoOpListener),
    AllStoneTools(::NoOpListener),
    AllTypesOfDoorsIncludingTrapdoors(::NoOpListener),
    AllWoodTools(::NoOpListener),
    AnyChainArmor(::NoOpListener),
    AnyConcreteBlock(::NoOpListener),
    AnyGlazedTerracotta(::NoOpListener),
    AnyTippedArrow(::NoOpListener),
    BarterWithPiglin(::NoOpListener),
    BlowUpBedInNether(::NoOpListener),
    BounceOnSlimeBlock(::NoOpListener),
    BreakDiamondTool(::NoOpListener),
    BreakPieceOfDiamondArmor(::NoOpListener),
    BreakShield(::NoOpListener),
    BreakAnyArmor(::NoOpListener),
    BreakAnyTool(::NoOpListener),
    BreedAxolotl(::NoOpListener),
    BreedBee(::NoOpListener),
    BreedCat(::NoOpListener),
    BreedChicken(::NoOpListener),
    BreedCow(::NoOpListener),
    BreedDonkey(::NoOpListener),
    BreedFox(::NoOpListener),
    BreedGoat(::NoOpListener),
    BreedHoglin(::NoOpListener),
    BreedHorse(::NoOpListener),
    BreedLlama(::NoOpListener),
    BreedMule(::NoOpListener),
    BreedOcelot(::NoOpListener),
    BreedPanda(::NoOpListener),
    BreedPig(::NoOpListener),
    BreedRabbit(::NoOpListener),
    BreedSheep(::NoOpListener),
    BreedStrider(::NoOpListener),
    BreedTurtle(::NoOpListener),
    BreedWolf(::NoOpListener),
    BrewPotionOfFireResistance(::NoOpListener),
    BrewPotionOfHarming(::NoOpListener),
    BrewPotionOfHealing(::NoOpListener),
    BrewPotionOfInvisibility(::NoOpListener),
    BrewPotionOfLeaping(::NoOpListener),
    BrewPotionOfNightVision(::NoOpListener),
    BrewPotionOfRegeneration(::NoOpListener),
    BrewPotionOfSlowness(::NoOpListener),
    BrewPotionOfStrength(::NoOpListener),
    BrewPotionOfSwiftness(::NoOpListener),
    BrewPotionOfWaterBreathing(::NoOpListener),
    BrewPotionOfWeakness(::NoOpListener),
    BrewAnyLingeringPotion(::NoOpListener),
    CarvePumpkin(::NoOpListener),
    CleanBannerWithCauldron(::NoOpListener),
    CompleteMap(::NoOpListener),
    Cook4FoodOnCampfire(::NoOpListener),
    CraftActivatorRail(::NoOpListener),
    CraftAnvil(::NoOpListener),
    CraftArmorStand(::NoOpListener),
    CraftBeehive(::NoOpListener),
    CraftBlastFurnace(::NoOpListener),
    CraftBookshelf(::NoOpListener),
    CraftCake(::NoOpListener),
    CraftCampfire(::NoOpListener),
    CraftCandle(::NoOpListener),
    CraftCartographyTable(::NoOpListener),
    CraftClock(::NoOpListener),
    CraftCompass(::NoOpListener),
    CraftDaylightDetector(::NoOpListener),
    CraftDispenser(::NoOpListener),
    CraftDropper(::NoOpListener),
    CraftEndCrystal(::NoOpListener),
    CraftEnderChest(::NoOpListener),
    CraftFireCharge(::NoOpListener),
    CraftFletchingTable(::NoOpListener),
    CraftGrindstone(::NoOpListener),
    CraftHoneyBlock(::NoOpListener),
    CraftHopper(::NoOpListener),
    CraftJackOlantern(::NoOpListener),
    CraftJukebox(::NoOpListener),
    CraftLectern(::NoOpListener),
    CraftLoom(::NoOpListener),
    CraftMagmaCream(::NoOpListener),
    CraftNoteBlock(::NoOpListener),
    CraftObserver(::NoOpListener),
    CraftPainting(::NoOpListener),
    CraftPiston(::NoOpListener),
    CraftPoweredRail(::NoOpListener),
    CraftPrismarineBrick(::NoOpListener),
    CraftRabbitStew(::NoOpListener),
    CraftRedNetherBrick(::NoOpListener),
    CraftRedstoneComparator(::NoOpListener),
    CraftRedstoneLamp(::NoOpListener),
    CraftRedstoneRepeater(::NoOpListener),
    CraftRespawnAnchor(::NoOpListener),
    CraftScaffolding(::NoOpListener),
    CraftSmoker(::NoOpListener),
    CraftSoulCampfire(::NoOpListener),
    CraftSoulLantern(::NoOpListener),
    CraftSpyglass(::NoOpListener),
    CraftStickyPiston(::NoOpListener),
    CraftStonecutter(::NoOpListener),
    CraftTarget(::NoOpListener),
    CraftTrappedChest(::NoOpListener),
    CreateDirtPathBlock(::NoOpListener),
    DestroyMobSpawner(::NoOpListener),
    Die(::NoOpListener),
    DrinkHoneyBottle(::NoOpListener),
    DrinkMilk(::NoOpListener),
    DrySponge(::NoOpListener),
    DyeLeatherArmorPiece(::NoOpListener),
    DyeSheep(::NoOpListener),
    EatApple(::NoOpListener),
    EatBakedPotato(::NoOpListener),
    EatBeetroot(::NoOpListener),
    EatBeetrootSoup(::NoOpListener),
    EatBread(::NoOpListener),
    EatCarrot(::NoOpListener),
    EatChorusFruit(::NoOpListener),
    EatCookedBeef(::NoOpListener),
    EatCookedChicken(::NoOpListener),
    EatCookedCod(::NoOpListener),
    EatCookedMutton(::NoOpListener),
    EatCookedPorkchop(::NoOpListener),
    EatCookedRabbit(::NoOpListener),
    EatCookedSalmon(::NoOpListener),
    EatCookie(::NoOpListener),
    EatDriedKelp(::NoOpListener),
    EatEnchantedGoldenApple(::NoOpListener),
    EatGlowBerry(::NoOpListener),
    EatGoldenApple(::NoOpListener),
    EatGoldenCarrot(::NoOpListener),
    EatMelonSlice(::NoOpListener),
    EatMushroomStew(::NoOpListener),
    EatPoisonPotato(::NoOpListener),
    EatPotato(::NoOpListener),
    EatPufferfish(::NoOpListener),
    EatPumpkinPie(::NoOpListener),
    EatRabbitStew(::NoOpListener),
    EatRawBeef(::NoOpListener),
    EatRawChicken(::NoOpListener),
    EatRawCod(::NoOpListener),
    EatRawMutton(::NoOpListener),
    EatRawPorkchop(::NoOpListener),
    EatRawRabbit(::NoOpListener),
    EatRawSalmon(::NoOpListener),
    EatRottenFlesh(::NoOpListener),
    EatSpiderEye(::NoOpListener),
    EatSuspiciousStew(::NoOpListener),
    EatSweetBerry(::NoOpListener),
    EatTropicalFish(::NoOpListener),
    EnchantBook(::NoOpListener),
    EnchantFishingPole(::NoOpListener),
    EnchantWoodenTool(::NoOpListener),
    EnterBadlandsBiome(::NoOpListener),
    EnterBambooJungleBiome(::NoOpListener),
    EnterDesertTemple(::NoOpListener),
    EnterDesertVillage(::NoOpListener),
    EnterDungeon(::NoOpListener),
    EnterEndCity(::NoOpListener),
    EnterIceSpikesBiome(::NoOpListener),
    EnterIgloo(::NoOpListener),
    EnterJungleBiome(::NoOpListener),
    EnterJungleTemple(::NoOpListener),
    EnterLargeTreeTaigaBiome(::NoOpListener),
    EnterMushroomIslandBiome(::NoOpListener),
    EnterPlainsVillage(::NoOpListener),
    EnterRavine(::NoOpListener),
    EnterSavannaVillage(::NoOpListener),
    EnterShatteredSavannaBiome(::NoOpListener),
    EnterShipwreck(::NoOpListener),
    EnterTaigaVillage(::NoOpListener),
    EnterTundraBiome(::NoOpListener),
    EnterTundraVillage(::NoOpListener),
    EnterWarmOceanBiome(::NoOpListener),
    EnterWitchHut(::NoOpListener),
    EnterAmethystGeode(::NoOpListener),
    EquipCurseOfBindingItem(::NoOpListener),
    FeedWheatToHorse(::NoOpListener),
    FillComposter(::NoOpListener),
    FullDiamondArmor(::NoOpListener),
    FullGoldArmor(::NoOpListener),
    FullIronArmor(::NoOpListener),
    FullLeatherArmor(::NoOpListener),
    FullNetheriteArmor(::NoOpListener),
    GetSkeletonToShootSkeleton(::NoOpListener),
    GetAbsorptionEffect(::NoOpListener),
    GetBlindnessEffect(::NoOpListener),
    GetDolphinsGraceEffect(::NoOpListener),
    GetGlowingEffect(::NoOpListener),
    GetHungerEffect(::NoOpListener),
    GetLevitationEffect(::NoOpListener),
    GetMiningFatigueEffect(::NoOpListener),
    GetRegenerationEffect(::NoOpListener),
    GetResistanceEffect(::NoOpListener),
    GetWitherEffect(::NoOpListener),
    GrowDarkOakTree(::NoOpListener),
    GrowGiantMushroom(::NoOpListener),
    GrowLargeJungleTree(::NoOpListener),
    GrowLargeSpruceTree(::NoOpListener),
    HaveDolphinLeadYouToTreasure(::NoOpListener),
    HitYourselfWithArrow(::NoOpListener),
    KillAxolotl(::NoOpListener),
    KillBabyVillager(::NoOpListener),
    KillBabyZombieWithArrow(::NoOpListener),
    KillBat(::NoOpListener),
    KillBee(::NoOpListener),
    KillBlaze(::NoOpListener),
    KillBlazeWithSnowballs(::NoOpListener),
    KillCat(::NoOpListener),
    KillCaveSpider(::NoOpListener),
    KillChicken(::NoOpListener),
    KillCod(::NoOpListener),
    KillCow(::NoOpListener),
    KillCreeper(::NoOpListener),
    KillCreeperWithAnotherCreeper(::NoOpListener),
    KillCreeperWithTnt(::NoOpListener),
    KillDolphin(::NoOpListener),
    KillDonkey(::NoOpListener),
    KillDrowned(::NoOpListener),
    KillDrownedHoldingTrident(::NoOpListener),
    KillElderGuardian(::NoOpListener),
    KillEnderDragon(::NoOpListener),
    KillEnderDragonWithoutBeds(::NoOpListener),
    KillEnderman(::NoOpListener),
    KillEndermite(::NoOpListener),
    KillEvoker(::NoOpListener),
    KillFox(::NoOpListener),
    KillGhast(::NoOpListener),
    KillGlowSquid(::NoOpListener),
    KillGuardian(::NoOpListener),
    KillHoglin(::NoOpListener),
    KillHorse(::NoOpListener),
    KillHusk(::NoOpListener),
    KillIronGolem(::NoOpListener),
    KillLlama(::NoOpListener),
    KillMagmaCube(::NoOpListener),
    KillMobWhileItsOnFire(::NoOpListener),
    KillMobWithTamedWolf(::NoOpListener),
    KillMobWithDripstone(::NoOpListener),
    KillMobWithFallDamage(::NoOpListener),
    KillMooshroom(::NoOpListener),
    KillMule(::NoOpListener),
    KillOcelot(::NoOpListener),
    KillPanda(::NoOpListener),
    KillParrot(::NoOpListener),
    KillPhantom(::NoOpListener),
    KillPig(::NoOpListener),
    KillPiglin(::NoOpListener),
    KillPiglinBrute(::NoOpListener),
    KillPillager(::NoOpListener),
    KillPolarBear(::NoOpListener),
    KillPufferfish(::NoOpListener),
    KillRabbit(::NoOpListener),
    KillRavager(::NoOpListener),
    KillSalmon(::NoOpListener),
    KillSheep(::NoOpListener),
    KillShulker(::NoOpListener),
    KillSilverfish(::NoOpListener),
    KillSkeleton(::NoOpListener),
    KillSkeletonWithoutItDamagingYou(::NoOpListener),
    KillSlime(::NoOpListener),
    KillSnowGolem(::NoOpListener),
    KillSpider(::NoOpListener),
    KillSpiderJockey(::NoOpListener),
    KillSquid(::NoOpListener),
    KillStray(::NoOpListener),
    KillStrider(::NoOpListener),
    KillTropicalFish(::NoOpListener),
    KillTurtle(::NoOpListener),
    KillVex(::NoOpListener),
    KillVillager(::NoOpListener),
    KillVindicator(::NoOpListener),
    KillWitch(::NoOpListener),
    KillWither(::NoOpListener),
    KillWitherSkeleton(::NoOpListener),
    KillWolf(::NoOpListener),
    KillZoglin(::NoOpListener),
    KillZombie(::NoOpListener),
    KillZombiePiglin(::NoOpListener),
    KillZombieVillager(::NoOpListener),
    LightCreeperWithFlintSteel(::NoOpListener),
    LightTntWithFlintSteel(::NoOpListener),
    LightTntWithRedstone(::NoOpListener),
    LootBuriedTreasure(::NoOpListener),
    LootRuinedPortalChest(::NoOpListener),
    MakeEfficiency5Tool(::NoOpListener),
    MakePower5Bow(::NoOpListener),
    MakeSharpness5Sword(::NoOpListener),
    MakeWitchPoisonItself(::NoOpListener),
    MineAncientDebris(::NoOpListener),
    MineCoalOre(::NoOpListener),
    MineCopperOre(::NoOpListener),
    MineDiamondOre(::NoOpListener),
    MineEmeraldOre(::NoOpListener),
    MineGoldOre(::NoOpListener),
    MineIronOre(::NoOpListener),
    MineLapisLazuliOre(::NoOpListener),
    MineNetherGoldOre(::NoOpListener),
    MineNetherQuartzOre(::NoOpListener),
    MineRedstoneOre(::NoOpListener),
    Obtain12UniqueFlowers(::NoOpListener),
    ObtainAmethystShard(::NoOpListener),
    ObtainMendingBook(::NoOpListener),
    ObtainNameTag(::NoOpListener),
    ObtainNautilusShell(::NoOpListener),
    ObtainSaddle(::NoOpListener),
    ObtainTrident(::NoOpListener),
    ObtainAnyMobHead(::NoOpListener),
    ObtainDiamondHorseArmor(::NoOpListener),
    ObtainGoldHorseArmor(::NoOpListener),
    ObtainIronHorseArmor(::NoOpListener),
    ObtainLeatherHorseArmor(::NoOpListener),
    PlantBamboo(::NoOpListener),
    PlantBeetrootSeed(::NoOpListener),
    PlantChorusFruit(::NoOpListener),
    PlantCocoaBean(::NoOpListener),
    PlantNetherWart(::NoOpListener),
    PlantPumpkinSeed(::NoOpListener),
    PlantSugarCane(::NoOpListener),
    PlantWheatSeed(::NoOpListener),
    PlantAnySapling(::NoOpListener),
    PlantSomethingInFlowerPot(::NoOpListener),
    PlayMusicDisc(::NoOpListener),
    PushMobWithPiston(::NoOpListener),
    ReachLevel10(::NoOpListener),
    ReachLevel25(::NoOpListener),
    ReachBuildLimitY256(::NoOpListener),
    ReachY0InEnd(::NoOpListener),
    RepairToolInAnvil(::NoOpListener),
    RideBoatWithCreeper(::NoOpListener),
    RideMinecartOnRail(::NoOpListener),
    RidePig(::NoOpListener),
    RingBell(::NoOpListener),
    SetYourSpawnWithBed(::NoOpListener),
    ShearMooshroom(::NoOpListener),
    ShearSheep(::NoOpListener),
    ShootBatWithArrow(::NoOpListener),
    ShootBell(::NoOpListener),
    ShootFireworkFromCrossbow(::NoOpListener),
    StandOnBedrock(::NoOpListener),
    StareAtSunWithSpyglass(::NoOpListener),
    StripLog(::NoOpListener),
    SwimInDesertWell(::NoOpListener),
    SwimInLavaWithFireResistance(::NoOpListener),
    TameCat(::NoOpListener),
    TameDonkey(::NoOpListener),
    TameHorse(::NoOpListener),
    TameLlama(::NoOpListener),
    TameMule(::NoOpListener),
    TameParrot(::NoOpListener),
    TameWolf(::NoOpListener),
    ThrowDiamondInLava(::NoOpListener),
    ThrowEnderPearl(::NoOpListener),
    ThrowSnowball(::NoOpListener),
    ThrowEgg(::NoOpListener),
    TrapMobInBoat(::NoOpListener),
    UseAnyDyeOnSign(::NoOpListener),
    UseBonemealOnGrass(::NoOpListener),
    WearCarvedPumpkin(::NoOpListener),
    WriteBook(::NoOpListener),
    Unknown(::NoOpListener);

    fun addListener(state: State, player: Player): ObjectiveListener {
        val listener = listenerFactory(state, this, player)
        Bukkit.getServer().pluginManager.registerEvents(listener, state.plugin)
        return listener
    }
}
